"""
YAPAY ZEKA DESTEKLİ ÖNERİ MOTORU
Tehlike türüne göre otomatik mühendislik/idari tedbir, KKD, eğitim vb. önerileri üretir.
"""

import json

# Kategori bazında öneri şablonları
SUGGESTION_TEMPLATES = {
    "Fiziksel Riskler": {
        "engineering_measures": [
            "Gürültü kaynağının izolasyonu (ses yalıtım kabini, perde)",
            "Makine bakım programı ile gürültü/titreşim kontrolü",
            "Havalandırma sistemi iyileştirmesi",
            "Toz emme sistemi (lokal egzoz havalandırması)",
            "İklimlendirme sistemi kurulumu",
            "Aydınlatma seviyesinin standarda uygun hale getirilmesi",
            "Titreşim sönümleyici ekipman montajı",
            "Ses geçirmez bariyer/ kabin kurulumu",
            "Radyasyon koruyucu kalkan/ekran kullanımı",
            "Termal konfor için yalıtım ve havalandırma iyileştirmesi",
        ],
        "administrative_measures": [
            "Gürültü maruziyet süresinin sınırlandırılması (rotasyon)",
            "Gürültü haritası oluşturulması",
            "Titreşim maruziyet süresinin sınırlandırılması",
            "Çalışma programının termal koşullara göre düzenlenmesi",
            "Düzenli mola imkanı sağlanması",
            "İş hijyeni ölçüm programı oluşturulması",
            "Periyodik sağlık muayene programı",
            "Uyarı levhaları ve ikaz sistemleri",
            "Talimat hazırlanması ve duyurulması",
            "Toz ölçümü ve analiz programı",
        ],
        "ppe": [
            "Kulak koruyucu (kulaklık / tıkaç) - SNR değeri uygun",
            "Toz maskesi (FFP2/FFP3)",
            "Titreşim önleyici eldiven",
            "UV koruyucu yüz siperi / kaynak maskesi",
            "UV koruyucu gözlük",
            "Radyasyon koruyucu önlük",
            "Sıcağa/soğuğa dayanıklı iş elbisesi",
            "Yalıtımlı çizme / eldiven",
            "Termal koruyucu giysi",
            "Güneş gözlüğü (UV korumalı)",
        ],
        "training": [
            "Gürültü ve işitme sağlığı eğitimi",
            "Kişisel koruyucu donanım kullanım eğitimi",
            "Termal konfor ve ısı stresi eğitimi",
            "Toz maruziyeti ve korunma yolları eğitimi",
            "Radyasyon güvenliği eğitimi",
            "İş hijyeni temel eğitimi",
        ],
        "health_surveillance": [
            "Odyometrik test (işitme muayenesi) - yılda 1 kez",
            "Solunum fonksiyon testi (SFT)",
            "Göz muayenesi",
            "Dermatolojik muayene",
            "Fiziksel muayene (termal stres için)",
            "Kan ve idrar tetkikleri",
        ],
        "measurement": [
            "Gürültü ölçümü (kişisel ve ortam)",
            "Titreşim ölçümü (el-kol ve tüm vücut)",
            "Aydınlatma ölçümü",
            "Termal konfor ölçümü",
            "Toz ölçümü (solunabilir ve solunmayan)",
            "Radyasyon ölçümü",
        ],
        "periodic_control": [
            "Havalandırma sistemi periyodik kontrolü",
            "Toz emme sistemi periyodik kontrolü",
            "İklimlendirme sistemi bakımı",
            "Aydınlatma armatürleri bakımı",
        ],
    },
    "Mekanik Riskler": {
        "engineering_measures": [
            "Makine koruyucu ekipmanları (sabit/hareketli koruyucu)",
            "Acil durdurma butonu (acil stop)",
            "İki el kontrol sistemi",
            "Fotoelektrik emniyet bariyeri",
            "Basınç hassas minder",
            "Kilitli koruyucu kapı",
            "Emniyet rölesi / PLC",
            "Konveyör emniyet sistemleri",
            "Vinç limit switch ve yük sensörü",
            "Mekanik kilitleme sistemleri",
            "Lazer emniyet sistemi",
            "Hidrolik/pnömatik emniyet valfleri",
            "Koruyucu çit/korkuluk",
            "Kaymaz zemin kaplaması",
            "Yürüme yollarının işaretlenmesi",
        ],
        "administrative_measures": [
            "Makine bakım planı oluşturulması",
            "Periyodik kontrol programı",
            "Çalışma talimatı hazırlanması",
            "Riskli bölgelere uyarı levhası",
            "Kullanım öncesi kontrol listesi (check-list)",
            "Kilit/Etiket (Lockout-Tagout) prosedürü",
            "İş izin sistemi",
            "Bakım ve onarım prosedürü",
            "Periyodik muayene takvimi",
            "Düzenli ev temizliği (housekeeping) programı",
        ],
        "ppe": [
            "Koruyucu başlık (baret)",
            "Koruyucu gözlük / yüz siperi",
            "Kesilmeye dayanıklı eldiven",
            "Koruyucu iş ayakkabısı (çelik burunlu)",
            "Tulum / iş elbisesi",
            "Dizlik",
            "Çelik burunlu çizme",
            "Yüksekte çalışma emniyet kemeri",
        ],
        "training": [
            "Makine güvenliği ve emniyet ekipmanları eğitimi",
            "Kilit/Etiket (Lockout-Tagout) eğitimi",
            "İş ekipmanlarının güvenli kullanım eğitimi",
            "El aletleri güvenli kullanım eğitimi",
            "Vinç ve kaldırma ekipmanı eğitimi",
            "Forklift operatör eğitimi",
            "Acil durum eğitimi",
        ],
        "health_surveillance": [
            "Fiziksel muayene",
            "Kulak burun boğaz muayenesi (gürültü varsa)",
            "Nörolojik muayene (titreşim maruziyeti)",
            "Ortopedik muayene",
            "El ve parmak muayenesi",
        ],
        "measurement": [
            "Makine risk değerlendirmesi (2006/42/AT)",
            "İş ekipmanı periyodik kontrol muayeneleri",
            "Topraklama ölçümü",
            "Basınçlı kap testleri",
        ],
        "periodic_control": [
            "İş ekipmanları periyodik kontrol (yılda en az 1 kez)",
            "Basınçlı kaplar periyodik kontrol",
            "Vinç periyodik kontrol (yılda 1 kez)",
            "Forklift periyodik kontrol (yılda 1 kez)",
            "Kaldırma ekipmanları periyodik kontrol",
            "Asansör periyodik kontrol (yılda 1 kez)",
        ],
    },
    "Elektrik Riskleri": {
        "engineering_measures": [
            "Kaçak akım koruma rölesi tesis edilmesi",
            "Topraklama sistemi tesis edilmesi",
            "Otomatik sigorta / NER koruma",
            "Atmosferik koruma (paratoner) sistemi",
            "Elektrik panolarının standartlara uygun hale getirilmesi",
            "Kablo kanalı / boru içi tesisat",
            "Sızdırmaz pano ve buatlar",
            "Aydınlatma armatürlerinin standartlara uygun hale getirilmesi",
            "Yalıtkan paspas",
            "Uyarı levhaları ve etiketleme",
            "Seyyar kablo yerine sabit tesisat",
            "Elektrik odasında kilit sistemi",
            "Ark korumalı pano sistemi",
            "UPS ve jeneratör bağlantısı",
        ],
        "administrative_measures": [
            "Elektrik tesisatı periyodik kontrol programı",
            "Topraklama ölçüm programı",
            "Elektrik iç tesisat projesi güncellemesi",
            "Yetkili elektrikçi görevlendirilmesi",
            "İş izin sistemi (elektrik çalışmaları için)",
            "Kilit/Etiket (Lockout-Tagout) prosedürü",
            "Bakım ve onarım talimatı",
            "Elektrik panosu tek hat şeması",
        ],
        "ppe": [
            "Yalıtkan eldiven (elektrikçi eldiveni)",
            "Yalıtkan çizme",
            "Yalıtkan paspas",
            "Ark koruyucu elbise",
            "Koruyucu yüz siperi (ark flaşına karşı)",
            "Koruyucu gözlük",
            "Gerilim dedektörü / kalem",
        ],
        "training": [
            "Elektrik güvenliği ve ilk yardım eğitimi",
            "Kilitleme/Etiketleme (Lockout-Tagout) eğitimi",
            "Statik elektrik ve korunma eğitimi",
            "Yangın söndürme eğitimi (elektrik yangınları)",
            "Temel elektrik bilgisi eğitimi",
            "Elektrik çarpmasında ilk yardım eğitimi",
        ],
        "health_surveillance": [
            "Genel sağlık muayenesi",
            "Göz muayenesi",
            "Kardiyolojik muayene (elektrik çarpması riski)",
        ],
        "measurement": [
            "Topraklama ölçümü (yılda en az 1 kez)",
            "Kaçak akım testi",
            "Yalıtım direnci ölçümü",
            "Paratoner periyodik kontrolü",
            "Termal kamera ile pano kontrolü",
        ],
        "periodic_control": [
            "Elektrik tesisatı periyodik kontrolü (yılda 1 kez)",
            "Topraklama ölçümü (yılda 1 kez)",
            "Paratoner kontrolü (yılda 1 kez)",
            "Kaçak akım rölesi testi (ayda 1 kez)",
            "Trafo bakım ve kontrolü",
        ],
    },
    "Kimyasal Riskler": {
        "engineering_measures": [
            "Lokal egzoz havalandırması (LEV) kurulumu",
            "Kimyasal depolama alanı iyileştirmesi (havalandırmalı, sızdırmaz zemin)",
            "Kimyasal muhafaza kabini (yanmaz, havalandırmalı)",
            "Davlumbaz / çeker ocak kurulumu",
            "Ac duruş sistemi",
            "Kimyasal dökülme seti (spill kit) temini",
            "Göz duşu ve acil duş kurulumu",
            "Otomatik algılama sistemi (gaz dedektörü)",
            "ATEX uyumlu ekipman",
            "Kimyasal nakil sistemleri (kapalı devre)",
            "Nötralizasyon sistemi",
            "Sıcaklık kontrol sistemi",
        ],
        "administrative_measures": [
            "Kimyasal envanteri oluşturulması",
            "Malzeme Güvenlik Bilgi Formu (MSDS/SDS) temini",
            "Kimyasal etiketleme sistemi",
            "Kimyasal uyumluluk tablosu",
            "Kimyasal elleçleme talimatı",
            "Sınırlı alan çalışma izni",
            "Kimyasal maruziyet ölçüm programı",
            "Depolama limitleri belirlenmesi",
            "Atık yönetim prosedürü",
            "Stok takip sistemi (FIFO)",
            "Kimyasal taşıma talimatı",
        ],
        "ppe": [
            "Kimyasal koruyucu eldiven (uygun malzeme)",
            "Kimyasal koruyucu gözlük / yüz siperi",
            "Kimyasal koruyucu tulum",
            "Kimyasal koruyucu çizme",
            "Solunum koruyucu (uygun filtreli maske)",
            "Gaz maskesi (uygun kartuşlu)",
            "Önlük / apron",
            "Kimyasal sıçramasına karşı koruyucu elbise",
        ],
        "training": [
            "Tehlikeli kimyasallar güvenli çalışma eğitimi",
            "SDS okuma ve anlama eğitimi",
            "Kimyasal dökülme acil müdahale eğitimi",
            "KKD kullanım eğitimi",
            "Kimyasal güvenlik eğitimi",
            "ATEX farkındalık eğitimi",
            "Tehlikeli atık yönetimi eğitimi",
        ],
        "health_surveillance": [
            "Periyodik sağlık muayenesi (yılda en az 1 kez)",
            "Solunum fonksiyon testi (SFT)",
            "Kan ve idrar tetkikleri (maruziyet biyomonitorizasyonu)",
            "Dermatolojik muayene",
            "Karaciğer ve böbrek fonksiyon testleri",
            "Akciğer grafisi",
        ],
        "measurement": [
            "Kimyasal maruziyet ölçümü (kişisel ve ortam)",
            "Havalandırma etkinlik ölçümü",
            "Gaz algılama sistemi kalibrasyonu",
            "Patlayıcı ortam ölçümü (ATEX)",
        ],
        "periodic_control": [
            "Havalandırma sistemi periyodik kontrolü",
            "Gaz dedektörü kalibrasyonu (6 ayda 1 kez)",
            "Acil duş / göz duşu haftalık test",
            "Kimyasal depolama alanı kontrolü",
            "Yangın söndürme ekipmanı kontrolü",
        ],
    },
    "Biyolojik Riskler": {
        "engineering_measures": [
            "Havalandırma sistemi (HEPA filtreli)",
            "Biyolojik güvenlik kabini (Sınıf II)",
            "El hijyeni istasyonu (sensörlü musluk)",
            "Otomatik el dezenfektanı",
            "Atık ayrıştırma sistemi",
            "Basınçlandırma sistemi (negatif/pozitif basınç)",
            "UV sterilizasyon sistemi",
            "Kesici-delici atık kutusu",
            "Otoklav sterilizasyon cihazı",
        ],
        "administrative_measures": [
            "Enfeksiyon kontrol prosedürü",
            "Atık yönetim planı",
            "Hijyen talimatı",
            "Maruziyet sonrası profilaksi prosedürü",
            "Bağışıklama programı",
            "Bildirim prosedürü",
            "Temizlik ve dezenfeksiyon programı",
            "İş elbisesi ayrı yıkama talimatı",
        ],
        "ppe": [
            "Tıbbi maske / N95 maske",
            "Koruyucu gözlük / siperlik",
            "Tek kullanımlık eldiven (nitril/lateks)",
            "Koruyucu önlük / tulum",
            "Bone / kep",
            "Kesilmeye dayanıklı eldiven (kesici-delici için)",
            "Yüz siperi",
        ],
        "training": [
            "Enfeksiyon kontrolü eğitimi",
            "El hijyeni eğitimi",
            "Atık yönetimi eğitimi",
            "Kesici-delici yaralanma önleme eğitimi",
            "Biyolojik etkenler ve korunma eğitimi",
            "KKD kullanım eğitimi",
        ],
        "health_surveillance": [
            "Hepatit B taraması ve aşılama",
            "Tetanos aşısı",
            "Periyodik sağlık muayenesi",
            "Akciğer grafisi",
            "Tüberkülin testi",
            "Kan tetkikleri",
        ],
        "measurement": [
            "Biyolojik etken ölçümü",
            "Hava mikrobiyolojisi ölçümü",
            "Su analizi",
            "Yüzey hijyen testi",
        ],
        "periodic_control": [
            "HVAC sistemi periyodik kontrolü",
            "HEPA filtre değişimi",
            "Otoklav periyodik kontrolü",
            "Sterilizasyon etkinlik testi",
        ],
    },
    "Ergonomik Riskler": {
        "engineering_measures": [
            "Ayarlanabilir çalışma masası/tezgahı",
            "Ergonomik sandalye temini",
            "Yük kaldırma yardımcı ekipmanı (vakumlu kaldırıcı, transpalet)",
            "Konveyör bant sistem kurulumu",
            "Yükseklik ayarlı çalışma platformu",
            "Ergonomik el aletleri temini",
            "Monitör standı ve doküman tutucu",
            "Ayak desteği",
            "Ergonomik klavye ve mouse",
            "Mekanik yardımcı ekipman (manipülatör, vinç)",
            "Bant hızı ayarlama imkanı",
        ],
        "administrative_measures": [
            "İş rotasyonu programı",
            "Düzenli mola planı",
            "Ergonomik risk değerlendirmesi (REBA, RULA, NIOSH)",
            "İş istasyonu düzenlemesi",
            "Çalışma hızının ayarlanması",
            "Kişi-iş uyumu değerlendirmesi",
            "Fiziksel kapasiteye uygun iş dağılımı",
        ],
        "ppe": [
            "Ergonomik eldiven",
            "Dizlik",
            "Bel desteği / korse",
            "Basınç azaltıcı ayak tabanlığı",
            "Anti-yorgunluk matı",
        ],
        "training": [
            "Ergonomi farkındalık eğitimi",
            "Doğru kaldırma teknikleri eğitimi",
            "Ofis ergonomisi eğitimi",
            "İstasyon düzenleme eğitimi",
            "Isınma ve germe egzersizleri eğitimi",
        ],
        "health_surveillance": [
            "Kas-İskelet Sistemi muayenesi",
            "Fizik muayene",
            "Ergonomik risk anketi",
            "Göz muayenesi (ekranlı araçlar için)",
        ],
        "measurement": [
            "Ergonomik risk değerlendirmesi (REBA/RULA/OWAS)",
            "NIOSH kaldırma analizi",
            "Ekranlı araç ergonomi değerlendirmesi",
        ],
        "periodic_control": [
            "Ergonomik iş istasyonu periyodik değerlendirmesi",
        ],
    },
    "Psikososyal Riskler": {
        "engineering_measures": [
            "Ses yalıtımı (gürültü stresini azaltmak için)",
            "Dinlenme alanı oluşturulması",
            "İyi aydınlatma ve havalandırma",
            "Ergonomik iş istasyonu",
            "Yeşil alan / dinlenme odası",
        ],
        "administrative_measures": [
            "Vardiya planının optimize edilmesi",
            "Çalışma saatlerinin düzenlenmesi",
            "İş yükü dağılımının iyileştirilmesi",
            "Geribildirim mekanizması kurulması",
            "Psikolojik destek hattı oluşturulması",
            "Mobbing önleme politikası",
            "Kriz yönetim planı",
            "Performans değerlendirme sisteminin iyileştirilmesi",
            "Oryantasyon programı",
            "Çalışan memnuniyeti anketi",
        ],
        "ppe": [],
        "training": [
            "Stres yönetimi eğitimi",
            "İletişim becerileri eğitimi",
            "Zaman yönetimi eğitimi",
            "Mobbing farkındalık eğitimi",
            "Liderlik eğitimi",
            "Çatışma yönetimi eğitimi",
            "Öfke kontrolü eğitimi",
        ],
        "health_surveillance": [
            "Psikolojik değerlendirme",
            "Stres seviyesi anketi",
            "Tükenmişlik sendromu değerlendirmesi",
        ],
        "measurement": [
            "Psikososyal risk değerlendirme anketi",
            "Çalışan memnuniyeti anketi",
            "İş stresi ölçeği",
        ],
        "periodic_control": [
            "Psikososyal risk periyodik değerlendirmesi",
        ],
    },
    "Yangın ve Patlama Riskleri": {
        "engineering_measures": [
            "Yangın algılama ve uyarı sistemi kurulumu",
            "Yangın söndürme sistemi (sprinkler, gazlı söndürme)",
            "Yangın tüpü temini ve konuşlandırılması",
            "ATEX uyumlu ekipman kullanımı",
            "Patlama önleyici sistem (ventilasyon, baskılama)",
            "Statik elektrik önleyici ekipman",
            "Yangın kapısı / duvarı",
            "Acil aydınlatma ve yönlendirme levhası",
            "Gaz algılama sistemi",
            "Yangın dolabı ve hidrant sistemi",
            "Paratoner sistemi",
            "Topraklama ve eşpotansiyel bağlantı",
            "Kıvılcım önleyici ekipman (ATEX)",
            "Yanıcı madde depolama dolabı",
        ],
        "administrative_measures": [
            "Acil durum planı hazırlanması",
            "Yangın tatbikatı planı (yılda en az 2 kez)",
            "Yangın söndürme ekipmanı periyodik kontrolü",
            "Sıcak iş izin sistemi",
            "ATEX risk değerlendirmesi (Patlama Koruma Dokümanı)",
            "Yangın algılama sistemi test planı",
            "Kaçış yollarının işaretlenmesi",
            "Yanıcı madde miktar sınırlaması",
            "Sigara içme yasağı ve alan belirleme",
        ],
        "ppe": [
            "Yangına dayanıklı elbise",
            "Yangın başlığı / kask",
            "Yangın eldiveni",
            "Yangın çizmesi",
            "Solunum koruyucu (acil durum maskesi)",
            "Isıya dayanıklı eldiven",
            "Yansıtıcı giysi",
        ],
        "training": [
            "Yangın güvenliği eğitimi",
            "Yangın söndürme cihazı kullanım eğitimi",
            "Acil durum ve tahliye eğitimi",
            "ATEX farkındalık eğitimi",
            "Sıcak iş izni eğitimi",
            "İlk yardım eğitimi",
            "Yangın tatbikat eğitimi (pratik)",
        ],
        "health_surveillance": [
            "Solunum fonksiyon testi (yangın söndürme görevlileri için)",
            "Genel sağlık muayenesi",
        ],
        "measurement": [
            "ATEX risk değerlendirmesi",
            "Patlayıcı ortam ölçümü",
            "Yangın algılama sistemi testi",
            "Yangın söndürme sistem basınç testleri",
        ],
        "periodic_control": [
            "Yangın tüpü periyodik kontrolü (yılda 1 kez, basınç testi)",
            "Yangın algılama sistemi periyodik kontrolü",
            "Sprinkler sistemi periyodik kontrolü",
            "Acil aydınlatma periyodik testi",
            "Paratoner periyodik kontrolü (yılda 1 kez)",
            "Gaz dedektörü kalibrasyonu (6 ayda 1 kez)",
            "Yangın kapıları periyodik kontrolü",
        ],
    },
    "Çevresel Riskler": {
        "engineering_measures": [
            "Atık su arıtma tesisi",
            "Tehlikeli atık depolama alanı (sızdırmaz zemin, çatı)",
            "Atık ayrıştırma istasyonu",
            "Sızdırmaz ikincil muhafaza sistemi",
            "Baca filtresi / toz tutucu sistem",
            "Gürültü bariyeri / izolasyonu",
            "Sıcaklık/nem kontrol sistemi",
            "Su geri kazanım sistemi",
        ],
        "administrative_measures": [
            "Atık yönetim planı",
            "Çevre yönetim sistemi (ISO 14001)",
            "Atık takip formu",
            "Çevresel etki değerlendirme raporu",
            "Atık beyanı (MoTAT, ETBİLD)",
            "Su ve enerji verimliliği programı",
            "Sıfır atık yönetim sistemi",
        ],
        "ppe": [
            "Kimyasal koruyucu eldiven (atık elleçleme için)",
            "Koruyucu gözlük",
            "Koruyucu tulum",
            "Çelik burunlu çizme",
        ],
        "training": [
            "Atık yönetimi eğitimi",
            "Tehlikeli atık eğitimi",
            "Çevre bilinci eğitimi",
            "Sıfır atık eğitimi",
            "Acil müdahale eğitimi (çevresel)",
        ],
        "health_surveillance": [
            "Periyodik sağlık muayenesi (atık çalışanları)",
            "Hepatit aşısı",
            "Tetanos aşısı",
        ],
        "measurement": [
            "Emisyon ölçümü",
            "Atık su analizi",
            "Gürültü ölçümü (çevresel)",
            "Toprak analizi",
            "Hava kalitesi ölçümü",
        ],
        "periodic_control": [
            "Atık su arıtma tesisi periyodik kontrolü",
            "Baca periyodik kontrolü",
            "Tehlikeli atık depolama alanı kontrolü",
        ],
    },
    "Yüksekte Çalışma Riskleri": {
        "engineering_measures": [
            "Yatay ve düşey yaşam hattı kurulumu",
            "Korkuluk sistemi",
            "İskele kurulumu (projelendirilmiş)",
            "Düşme durdurma sistemi (fall arrest)",
            "Güvenli çalışma platformu",
            "Sepetli vinç / platform",
            "Emniyet ağı",
            "Merdiven güvenlik kilidi",
            "Çatı güvenlik sistemi",
            "Kapak ve açıklıklara koruyucu kapak",
        ],
        "administrative_measures": [
            "Yüksekte çalışma izin sistemi",
            "Yüksekte çalışma talimatı",
            "Hava koşulları takibi (rüzgar, yağmur)",
            "Ekipman kullanım öncesi kontrol listesi",
            "Gözetmen atanması",
            "Saha düzeni ve uyarı bantları",
            "Yüksekte çalışan sayısı sınırlaması",
        ],
        "ppe": [
            "Emniyet kemeri (tam vücut - EN 361)",
            "Emniyet kemeri bağlantı lanyard'ı (EN 354/355)",
            "Enerji emici (EN 355)",
            "Kask (çene bağlı - EN 397)",
            "Koruyucu gözlük",
            "Kaymaz tabanlı iş ayakkabısı",
            "Yaşam hattı (EN 353-1/2)",
            "Gerilebilir tip düşme durdurucu (EN 360)",
        ],
        "training": [
            "Yüksekte güvenli çalışma eğitimi (teorik+pratik)",
            "Emniyet kemeri kullanım eğitimi",
            "İskele kurulum ve söküm eğitimi",
            "Merdiven güvenli kullanım eğitimi",
            "Acil kurtarma eğitimi",
            "İlk yardım eğitimi",
        ],
        "health_surveillance": [
            "Yüksekte çalışmaya uygunluk muayenesi",
            "Vestibüler (denge) testi",
            "Yükseklik korkusu değerlendirmesi",
            "Genel sağlık muayenesi",
            "Görme ve işitme testi",
        ],
        "measurement": [
            "Yüksekte çalışma ekipmanları periyodik muayenesi",
            "İskele periyodik kontrolü",
        ],
        "periodic_control": [
            "Emniyet kemeri periyodik kontrolü (6 ayda 1 kez)",
            "Yaşam hattı periyodik kontrolü (yılda 1 kez)",
            "İskele periyodik kontrolü (kurulumda ve haftalık)",
            "Merdiven periyodik kontrolü",
            "Düşme durdurma sistemi periyodik kontrolü (yılda 1 kez)",
        ],
    },
    "Nakliye ve Trafik Riskleri": {
        "engineering_measures": [
            "Araç-yaya ayrımı (bariyer, çizgi)",
            "Trafik aynası",
            "Forklift uyarı sistemi (sesli/ışıklı)",
            "Hız kesici tümsek",
            "Yükleme rampası güvenlik sistemi",
            "Geri görüş kamerası / sensör",
            "ADR uyumlu araç ekipmanları",
            "Trafik işaret ve levhaları",
            "Yaya yolu işaretlemesi",
            "Park alanı düzenlemesi",
            "Aydınlatmalı yaya geçidi",
        ],
        "administrative_measures": [
            "Tesis içi trafik kuralları talimatı",
            "Araç hız limiti belirlenmesi (20 km/s)",
            "Forklift operatör belgesi kontrolü",
            "Araç periyodik bakım programı",
            "ADR eğitimi ve belgesi (tehlikeli madde taşımacılığı)",
            "Yükleme-boşaltma talimatı",
            "Sürücü çalışma süreleri takibi (tako grafi)",
            "Araç günlük kontrol listesi",
        ],
        "ppe": [
            "Yansıtıcı yelek",
            "Koruyucu başlık (şantiye sahası)",
            "Koruyucu gözlük",
            "Çelik burunlu çizme",
            "İş elbisesi (yansıtıcılı)",
        ],
        "training": [
            "Forklift operatör eğitimi ve sertifikası",
            "Tesis içi trafik güvenliği eğitimi",
            "ADR eğitimi (tehlikeli madde taşıma)",
            "Defansif sürüş eğitimi",
            "Yükleme-boşaltma güvenliği eğitimi",
        ],
        "health_surveillance": [
            "Sürücü sağlık muayenesi (periyodik)",
            "Görme testi",
            "Psikoteknik değerlendirme",
        ],
        "measurement": [
            "Tesis içi gürültü ölçümü",
            "Emisyon ölçümü (egzoz)",
        ],
        "periodic_control": [
            "Forklift periyodik kontrolü (yılda 1 kez)",
            "Araç periyodik bakımı",
            "Vinç periyodik kontrolü",
            "Yangın söndürme cihazı periyodik kontrolü (araçlarda)",
        ],
    },
    "İnşaat ve Yapı Riskleri": {
        "engineering_measures": [
            "İskele kurulumu (projeye uygun, belgeli)",
            "Kazı destek sistemi (palplanş, iksa)",
            "Düşme koruma sistemi (korkuluk, emniyet ağı)",
            "Şantiye çevre güvenliği (çit, bariyer)",
            "Geçici yol ve yaya yolu",
            "Vinç güvenlik ekipmanları",
            "Beton kalıp destek sistemi",
            "Toz kontrol sistemi (su püskürtme)",
            "Şantiye aydınlatması",
            "Acil durum toplanma alanı",
            "Tehlikeli bölge işaretlemesi",
        ],
        "administrative_measures": [
            "İş izin sistemi (sıcak iş, kazı, yüksekte)",
            "Günlük saha kontrol listesi",
            "Haftalık İSG toplantı tutanağı",
            "Şantiye sahası giriş kontrolü",
            "İş programı ve İSG entegrasyonu",
            "Alt yüklenici İSG yeterlilik kontrolü",
            "Kazı öncesi yer altı görüntüleme",
            "Risk değerlendirme güncellemesi (her aşama için)",
            "Çalışan bilgilendirme (toolbox talk)",
        ],
        "ppe": [
            "Baret (EN 397)",
            "Koruyucu gözlük (EN 166)",
            "Yüksek görünürlüklü yelek (EN 471)",
            "Çelik burunlu çizme (EN ISO 20345)",
            "Emniyet kemeri (yüksekte çalışma için)",
            "Toz maskesi (FFP2/FFP3)",
            "Koruyucu eldiven",
            "Dizlik",
            "İş elbisesi",
        ],
        "training": [
            "İnşaat İSG eğitimi",
            "Yüksekte güvenli çalışma eğitimi",
            "Vinç operatör eğitimi",
            "Kazı güvenliği eğitimi",
            "Acil durum eğitimi",
            "KKD kullanım eğitimi",
            "Toolbox talk eğitimleri",
        ],
        "health_surveillance": [
            "İnşaat işçisi periyodik sağlık muayenesi",
            "Yüksekte çalışma uygunluk muayenesi",
            "Solunum fonksiyon testi",
            "İşitme testi",
            "Tetanos aşısı",
        ],
        "measurement": [
            "Toz ölçümü",
            "Gürültü ölçümü",
            "Titreşim ölçümü",
            "Yapısal güvenlik testleri",
        ],
        "periodic_control": [
            "İskele periyodik kontrolü (kurulumda, haftalık)",
            "Vinç periyodik kontrolü (yılda 1 kez)",
            "Kaldırma ekipmanı periyodik kontrolü",
            "Elektrik tesisatı periyodik kontrolü",
            "İş ekipmanları periyodik kontrolü",
        ],
    },
}


def get_suggestions(hazard_category_name):
    """Tehlike kategorisine göre önerileri getir"""
    return SUGGESTION_TEMPLATES.get(hazard_category_name, {
        "engineering_measures": ["Özel mühendislik önlemi gerektirir (uzman değerlendirmesi)"],
        "administrative_measures": ["Özel idari önlem gerektirir (uzman değerlendirmesi)"],
        "ppe": ["KKD gereksinimi uzman tarafından belirlenmelidir"],
        "training": ["Eğitim ihtiyacı uzman tarafından belirlenmelidir"],
        "health_surveillance": ["Sağlık gözetimi ihtiyacı değerlendirilmelidir"],
        "measurement": ["Ölçüm gerekliliği değerlendirilmelidir"],
        "periodic_control": ["Periyodik kontrol gerekliliği değerlendirilmelidir"],
    })


def format_suggestions(risk, hazard_category_name):
    """Risk kaydına eklenmek üzere önerileri JSON formatında hazırla"""
    suggestions = get_suggestions(hazard_category_name)
    return json.dumps(suggestions, ensure_ascii=False, indent=2)
