# -*- coding: utf-8 -*-
"""ISG Pro 2026 egitim sektor katalogu — OSGB Suite egitim modulune aktarildi.

Kaynak: docs/transfer-prep/isg-pro-2026/.../egitim/sector_catalog.py
Degisiklik: yalnizca bu dosyaya dokunulur; Suite API bu katalogu kullanir.
"""

SEKTOR_GRUPLARI = [
    ("A", [
        ("acik_maden", "Açık Maden, Taş Ocağı ve Agrega"),
        ("agac_isleri_marangozluk", "Ağaç İşleri / Marangozluk"),
        ("ahsap_mobilya_uretimi", "Ahşap / Mobilya Üretimi"),
        ("ahsap_mobilya", "Ahşap ve Mobilya Üretimi"),
        ("akaryakit_lpg_dolum_istasyonu", "Akaryakıt / LPG / Dolum İstasyonu"),
        ("aku_uretimi", "Akü ve Batarya Üretimi"),
        ("alisveris_merkezi_avm", "Alışveriş Merkezi / AVM"),
        ("aluminyum_profil_isleme", "Alüminyum / Profil İşleme"),
        ("ambalaj_paketleme", "Ambalaj / Paketleme"),
        ("asansor_montaj_ve_bakim", "Asansör / Montaj ve Bakım"),
        ("atik_yonetimi_geri_donusum", "Atık Yönetimi / Geri Dönüşüm"),
        ("atik_geri_donusum", "Atık Yönetimi ve Geri Dönüşüm"),
        ("avukatlik_hukuk_burosu", "Avukatlık / Hukuk Bürosu"),
        ("ayakkabi_deri_uretimi", "Ayakkabı / Deri Üretimi"),
    ]),
    ("B", [
        ("bakim_onarim_teknik_servis", "Bakım-Onarım / Teknik Servis"),
        ("balikcilik_su_urunleri", "Balıkçılık / Su Ürünleri"),
        ("banka_finans_2", "Banka / Finans"),
        ("banka_finans", "Banka, Finans ve Çağrı Merkezi"),
        ("basin_yayin_medya", "Basın / Yayın / Medya"),
        ("belediye_kamu_hizmetleri", "Belediye / Kamu Hizmetleri"),
        ("belediye", "Belediye, Kamu ve Saha Hizmetleri"),
        ("beton_cimento_hazir_beton", "Beton / Çimento / Hazır Beton"),
        ("bilisim_yazilim_it", "Bilişim / Yazılım / IT"),
        ("boyahaneler_boya_uretimi", "Boyahaneler / Boya Üretimi"),
    ]),
    ("C", [
        ("cam_seramik_porselen", "Cam / Seramik / Porselen"),
        ("cam_seramik", "Cam, Seramik ve Taş Ürünleri"),
    ]),
    ("Ç", [
        ("cagri_merkezi_contact_center", "Çağrı Merkezi / Contact Center"),
        ("celik_yapi_metal_konstruksiyon", "Çelik Yapı / Metal Konstrüksiyon"),
        ("cimento_klinker", "Çimento / Klinker"),
        ("cimento_beton", "Çimento, Beton ve Prefabrik"),
    ]),
    ("D", [
        ("dagitim_kargo_kurye", "Dağıtım / Kargo / Kurye"),
        ("demir_celik_hadde", "Demir-Çelik / Hadde"),
        ("demiryolu", "Demiryolu, Metro ve Raylı Sistemler"),
        ("depo_lojistik", "Depo, Lojistik ve Dağıtım Merkezi"),
        ("depolama_lojistik_depo", "Depolama / Lojistik Depo"),
        ("diger_belirtilmemis", "Diğer / Belirtilmemiş"),
        ("dijital_baski_matbaa", "Dijital Baskı / Matbaa"),
        ("dogalgaz_enerji_dagitim", "Doğalgaz / Enerji Dağıtım"),
        ("dokum_metal", "Döküm, Metal ve Metal Kaplama"),
    ]),
    ("E", [
        ("eczane_medikal_satis", "Eczane / Medikal Satış"),
        ("egitim_okul_kurs", "Eğitim / Okul / Kurs"),
        ("elektrik_elektronik_uretim", "Elektrik / Elektronik Üretim"),
        ("elektrik_tesisat_pano_montaj", "Elektrik Tesisat / Pano Montaj"),
        ("elektrik_bakim", "Elektrik Tesisatı ve Bakım"),
        ("elektronik_atik_bertaraf", "Elektronik Atık / Bertaraf"),
        ("elektronik", "Elektronik, Beyaz Eşya ve Montaj"),
        ("enerji_jenerator_trafo", "Enerji / Jeneratör / Trafo"),
        ("enerji_uretim", "Enerji Üretim Tesisleri"),
        ("e_ticaret_depo_fulfillment", "E-ticaret / Depo Fulfillment"),
    ]),
    ("F", [
        ("fabrika_genel_imalat", "Fabrika / Genel İmalat"),
        ("firin_unlu_mamuller", "Fırın / Unlu Mamuller"),
    ]),
    ("G", [
        ("gemi_insa_tersane", "Gemi İnşa / Tersane"),
        ("genel_uretim", "Genel Fabrika ve Üretim"),
        ("gida_uretimi_isleme", "Gıda Üretimi / İşleme"),
        ("gida_uretim", "Gıda ve İçecek Üretimi"),
        ("yenilenebilir_enerji", "Güneş ve Rüzgâr Enerjisi"),
        ("guvenlik_hizmetleri", "Güvenlik Hizmetleri"),
        ("guzellik_kuafor_spa", "Güzellik / Kuaför / Spa"),
    ]),
    ("H", [
        ("haberlesme_telekomunikasyon", "Haberleşme / Telekomünikasyon"),
        ("saglik", "Hastane, Klinik ve Sağlık Hizmetleri"),
        ("havalimani_yer_hizmetleri", "Havalimanı / Yer Hizmetleri"),
        ("havacilik", "Havalimanı ve Havacılık Yer Hizmetleri"),
        ("hayvancilik_ciftlik", "Hayvancılık / Çiftlik"),
        ("hayvancilik", "Hayvancılık ve Hayvansal Üretim"),
        ("hazir_giyim_konfeksiyon", "Hazır Giyim / Konfeksiyon"),
        ("hirdavat_yapi_market", "Hırdavat / Yapı Market"),
    ]),
    ("İ", [
        ("ic_mimarlik_dekorasyon", "İç Mimarlık / Dekorasyon"),
        ("ilac_farmasotik_uretim", "İlaç / Farmasötik Üretim"),
        ("ilac_kozmetik", "İlaç, Kozmetik ve Medikal Üretim"),
        ("insaat_santiye", "İnşaat / Şantiye"),
        ("insaat", "İnşaat ve Şantiye"),
        ("iskele_kalip_yapi_ekipmani", "İskele / Kalıp / Yapı Ekipmanı"),
        ("is_makinesi_agir_ekipman", "İş Makinesi / Ağır Ekipman"),
    ]),
    ("K", [
        ("kablo_tel_uretimi", "Kablo / Tel Üretimi"),
        ("kagit_karton_uretimi", "Kağıt / Karton Üretimi"),
        ("kagit_matbaa", "Kâğıt, Ambalaj ve Matbaa"),
        ("kamu_kurumu_idare", "Kamu Kurumu / İdare"),
        ("karayolu_tasimacilik", "Karayolu Taşımacılığı ve Filo"),
        ("kaynakli_imalat", "Kaynaklı İmalat"),
        ("kimya_kimyasal_uretim", "Kimya / Kimyasal Üretim"),
        ("kimyasal_boya", "Kimya, Boya ve Kaplama"),
        ("konaklama_otel_pansiyon", "Konaklama / Otel / Pansiyon"),
        ("kozmetik_temizlik_urunleri", "Kozmetik / Temizlik Ürünleri"),
        ("kurye", "Kurye, Kargo ve Saha Dağıtımı"),
        ("kuyumculuk_mucevher", "Kuyumculuk / Mücevher"),
    ]),
    ("L", [
        ("laboratuvar_analiz", "Laboratuvar / Analiz"),
        ("laboratuvar", "Laboratuvar ve Araştırma Merkezi"),
        ("lastik_kaucuk", "Lastik / Kauçuk"),
        ("liman", "Liman, Terminal ve Konteyner Operasyonları"),
    ]),
    ("M", [
        ("madencilik_maden_ocagi", "Madencilik / Maden Ocağı"),
        ("makine_imalati", "Makine İmalatı"),
        ("makine_imalat", "Makine İmalatı ve Montaj"),
        ("market_perakende", "Market / Perakende"),
        ("metal_isleme_torna_freze", "Metal İşleme / Torna-Freze"),
        ("metal_yapi_elemanlari_toptan", "Metal Yapı Elemanları Toptan Ticareti"),
        ("mobilya_ev_tekstili", "Mobilya / Ev Tekstili"),
        ("muhendislik_proje_ofisi", "Mühendislik / Proje Ofisi"),
        ("muteahhitlik_taahhut", "Müteahhitlik / Taahhüt"),
    ]),
    ("N", [
        ("nakliye_karayolu_tasimaciligi", "Nakliye / Karayolu Taşımacılığı"),
    ]),
    ("O", [
        ("ofis_idari_hizmetler", "Ofis / İdari Hizmetler"),
        ("ofis", "Ofis ve İdari İşler"),
        ("egitim_kurumu", "Okul, Kurs ve Eğitim Kurumu"),
        ("organizasyon_etkinlik", "Organizasyon / Etkinlik"),
        ("ormancilik_kereste", "Ormancılık / Kereste"),
        ("ormancilik", "Ormancılık ve Ağaç Kesim İşleri"),
        ("turizm", "Otel, Konaklama ve Turizm"),
        ("oto_lastik_servis", "Oto Lastik / Servis"),
        ("otogaz_lpg_bayi", "Otogaz / LPG Bayi"),
        ("otomotiv_yedek_parca", "Otomotiv / Yedek Parça"),
        ("otomotiv_servis_bakim", "Otomotiv Servis / Bakım"),
        ("otomotiv", "Otomotiv Üretimi ve Servis"),
    ]),
    ("Ö", [
        ("ozel_guvenlik", "Özel Güvenlik"),
        ("guvenlik", "Özel Güvenlik Hizmetleri"),
    ]),
    ("P", [
        ("patlayici", "Patlayıcı, Mühimmat ve Piroteknik"),
        ("perakende", "Perakende, Market ve Mağazacılık"),
        ("petrol_rafineri_depolama", "Petrol / Rafineri / Depolama"),
        ("petrol_dogalgaz", "Petrol, Doğalgaz ve Rafineri"),
        ("plastik_enjeksiyon_ekstruzyon", "Plastik / Enjeksiyon / Ekstrüzyon"),
        ("plastik_kaucuk", "Plastik ve Kauçuk Ürünleri"),
    ]),
    ("R", [
        ("reklam_tabela_baski", "Reklam / Tabela / Baskı"),
        ("restoran_cafe_mutfak", "Restoran / Cafe / Mutfak"),
        ("restoran", "Restoran, Mutfak ve Toplu Yemek"),
    ]),
    ("S", [
        ("saglik_hastane_klinik", "Sağlık / Hastane / Klinik"),
        ("seramik_fayans", "Seramik / Fayans"),
        ("sigorta_broker", "Sigorta / Broker"),
        ("soguk_hava_deposu", "Soğuk Hava Deposu"),
        ("spor_tesisi_fitness", "Spor Tesisi / Fitness"),
        ("su_atiksu", "Su, Atıksu ve Arıtma Tesisleri"),
        ("sut_sut_urunleri", "Süt / Süt Ürünleri"),
    ]),
    ("T", [
        ("tarim_ziraat", "Tarım / Ziraat"),
        ("tarim", "Tarım, Sera ve Bitkisel Üretim"),
        ("tas_ocagi_maden_ocagi", "Taş Ocağı / Maden Ocağı"),
        ("tekstil_dokuma_boyama", "Tekstil / Dokuma / Boyama"),
        ("tekstil", "Tekstil ve Konfeksiyon"),
        ("telekomunikasyon_altyapi", "Telekomünikasyon Altyapı"),
        ("telekom", "Telekomünikasyon ve Saha Çalışmaları"),
        ("temizlik_facility_management", "Temizlik / Facility Management"),
        ("temizlik", "Temizlik ve Tesis Hizmetleri"),
        ("tersane_liman_hizmetleri", "Tersane / Liman Hizmetleri"),
        ("tersane", "Tersane, Gemi İnşa ve Onarım"),
        ("tip_dis_klinigi", "Tıp / Diş Kliniği"),
        ("ticaret_aracilik_ofis", "Ticari Aracılık / Ofis ve Saha"),
        ("tarimsal_urun_toptan", "Tarımsal Ürün Toptan Ticareti"),
        ("canli_hayvan_toptan", "Canlı Hayvan Toptan Ticareti"),
        ("gida_toptan_depo", "Gıda Toptan Ticareti / Depo"),
        ("tekstil_deri_toptan", "Tekstil ve Deri Toptan Ticareti"),
        ("elektrik_elektronik_toptan", "Elektrik ve Elektronik Toptan Ticareti"),
        ("kimyasal_toptan_depo", "Kimyasal Ürün Toptan Ticareti / Depo"),
        ("ecza_medikal_toptan", "Ecza ve Medikal Toptan Ticareti"),
        ("mobilya_ev_esyasi_toptan", "Mobilya ve Ev Eşyası Toptan Ticareti"),
        ("makine_ekipman_toptan", "Makine ve Ekipman Toptan Ticareti"),
        ("otomotiv_toptan", "Motorlu Taşıt ve Parça Toptan Ticareti"),
        ("yakit_toptan_depo", "Yakıt Toptan Ticareti ve Depolama"),
        ("yapi_malzemeleri_toptan", "Yapı Malzemeleri Toptan Ticareti"),
        ("atik_hurda_toptan", "Atık ve Hurda Toptan Ticareti"),
        ("genel_toptan_depo", "Genel Toptan Ticaret / Depo"),
        ("kimyasal_perakende", "Kimyasal ve Yanıcı Ürün Perakendesi"),
        ("toplu_tasima_ulasim", "Toplu Taşıma / Ulaşım"),
        ("turizm_seyahat", "Turizm / Seyahat"),
    ]),
    ("Ü", [
        ("universite_yuksekogretim", "Üniversite / Yükseköğretim"),
        ("uretim_imalathane_genel", "Üretim / İmalathane (Genel)"),
    ]),
    ("Y", [
        ("yapi_malzemeleri_uretimi", "Yapı Malzemeleri Üretimi"),
        ("yemek_uretimi_catering", "Yemek Üretimi / Catering"),
        ("yenilenebilir_enerji_gunes_ruzgar", "Yenilenebilir Enerji / Güneş-Rüzgar"),
        ("kapali_maden", "Yeraltı Madenciliği"),
        ("yiyecek_icecek_uretimi", "Yiyecek-İçecek Üretimi"),
        ("yol_altyapi_insaati", "Yol / Altyapı İnşaatı"),
        ("yol_asfalt", "Yol, Asfalt ve Altyapı"),
        ("yuksekte_calisma_cephe", "Yüksekte Çalışma / Cephe"),
    ]),
]

# Siralama, egitim suresi dagitiminda oncelik sirasidir. Ilk konular daha yuksek
# agirlik alir; sureler tehlike sinifi kurallarina gore hesaplanir.
SEKTOREL_EGITIM_KONULARI = {

    "aricilik": [
        "Arı sokmaları, alerjik reaksiyon ve anafilaksiye acil müdahale",
        "Koruyucu arıcılık kıyafeti, eldiven ve yüz siperi kullanımı",
        "Kovanların kaldırılması ve taşınmasında ergonomi",
        "Körük kullanımında duman, sıcak yüzey ve yangın riskleri",
        "Açık alanda sıcaklık, güneş, arazi ve ulaşım riskleri",
    ],
    "camasirhane_kuru_temizleme": [
        "Kuru temizleme solventleri ve temizlik kimyasallarıyla güvenli çalışma",
        "Ütü, pres, kazan, buhar ve sıcak yüzeylerde yanık riskleri",
        "Çamaşır makineleri, sıkma sistemleri ve hareketli ekipman güvenliği",
        "Kirli tekstilde biyolojik etkenler, hijyen ve çapraz bulaşma",
        "Islak zemin, elle taşıma, ergonomi, yangın ve havalandırma",
    ],
    "cenaze_hizmetleri": [
        "Biyolojik etkenler, enfeksiyon riski ve hijyen uygulamaları",
        "Cenazenin kaldırılması, taşınması ve ergonomik çalışma",
        "Dezenfektan ve koruyucu kimyasallarla güvenli çalışma",
        "Kesici-delici aletler, kişisel koruyucu donanım ve atık yönetimi",
        "Araçla nakil, mezarlık sahası, psikososyal riskler ve acil durumlar",
    ],
    "ekipman_kiralama": [
        "Kiralanan ekipmanın teslim öncesi kontrolü ve güvenli kullanım talimatları",
        "Yükleme-boşaltma, kaldırma ekipmanı ve araç trafiği riskleri",
        "Hasarlı ekipman, enerji izolasyonu ve bakım-onarım güvenliği",
        "Depolama, istifleme, elle taşıma ve ergonomi",
        "Yakıt, akü, yangın, sızıntı ve acil durum müdahalesi",
    ],
    "hayvanat_bahcesi": [
        "Vahşi hayvan saldırısı, kaçış ve güvenli bariyer sistemleri",
        "Zoonozlar, biyolojik etkenler, karantina ve hijyen",
        "Hayvan besleme, bakım ve temizlik çalışmalarında güvenlik",
        "Ziyaretçi alanları, araç trafiği, kayma-düşme ve kalabalık yönetimi",
        "Acil yakalama, tahliye, kişisel koruyucu donanım ve ilk yardım",
    ],
    "tutun_urunleri_uretimi": [
        "Tütün tozu, nikotin ve kimyasal katkılara maruziyet",
        "Kesme, kıyma, kurutma ve paketleme makinelerinde güvenlik",
        "Yanıcı toz, yangın, patlama ve uygun havalandırma",
        "Elle taşıma, tekrarlı işler, ergonomi ve gürültü",
        "Hijyen, kişisel koruyucu donanım ve acil durum uygulamaları",
    ],
    "veterinerlik": [
        "Hayvan ısırması, tekmesi, ezilme ve güvenli sabitleme yöntemleri",
        "Zoonozlar, biyolojik etkenler, karantina ve hijyen",
        "Kesici-delici aletler, ilaçlar, anestezik gazlar ve tıbbi atıklar",
        "Röntgen, sterilizasyon, laboratuvar ve elektrikli ekipman riskleri",
        "Hayvanların kaldırılması, ergonomi, kişisel koruyucu donanım ve acil müdahale",
    ],
    "aku_uretimi": [
        "Kurşun ve kurşun bileşikleriyle güvenli çalışma",
        "Sülfürik asit, elektrolit ve kimyasal sıçrama riskleri",
        "Akü şarjında hidrojen gazı, havalandırma ve patlama riski",
        "Kimyasal dökülme, göz duşu ve acil müdahale",
        "Hijyen, sağlık gözetimi ve uygun kişisel koruyucu donanım",
    ],
    "otomotiv": [
        "Pres, robotlu hücre ve hareketli hatlarda sıkışma riskleri",
        "Araç lifti, kriko ve bakım çukuru güvenliği",
        "Boya, solvent, kaynak dumanı ve kimyasal maruziyet",
        "Akü sökme-takma ve elektrikli araç yüksek gerilim riskleri",
        "Trafik, test sürüşü ve ergonomik montaj riskleri",
    ],
    "dokum_metal": [
        "Ergimiş metal, cüruf ve sıcak yüzey sıçramaları",
        "Pota, vinç, kaldırma ve askı ekipmanı güvenliği",
        "Döküm dumanı, metal tozu, gaz ve havalandırma",
        "Isı stresi, yanıklar ve uygun KKD kullanımı",
        "Kalıp bozma, çapak alma ve sıkışma-ezilme riskleri",
    ],
    "makine_imalat": [
        "Makine koruyucuları, emniyet tertibatları ve acil durdurma",
        "Kesilme, sıkışma, ezilme ve parça fırlaması riskleri",
        "Bakım ve ayarda enerji izolasyonu ile kilitleme-etiketleme",
        "Taşlama, kesme, matkap ve el aletleriyle güvenli çalışma",
        "Montaj, kaldırma-taşıma ve ergonomik zorlanmalar",
    ],
    "kaynakli_imalat": [
        "Kaynak ışını, göz-yüz koruması ve sıcak metal sıçraması",
        "Kaynak dumanı, gazlar ve lokal havalandırma",
        "Sıcak çalışma izni, kıvılcım kontrolü ve yangın gözcülüğü",
        "Basınçlı gaz tüpleri, regülatör ve hortum güvenliği",
        "Kapalı alanda kaynak, gaz ölçümü ve kurtarma planı",
    ],
    "kimyasal_boya": [
        "Kimyasal etiketler, SDS ve maruziyet yolları",
        "Solvent, izosiyanat, aerosol ve toksik buhar maruziyeti",
        "Yanıcı atmosfer, statik elektrik ve ex-proof ekipman",
        "Uyumsuz kimyasalların güvenli depolanması ve transferi",
        "Dökülme, sızıntı, acil duş ve müdahale prosedürleri",
    ],
    "plastik_kaucuk": [
        "Enjeksiyon, ekstrüzyon ve pres makinelerinde sıkışma",
        "Sıcak kalıp, eriyik polimer ve yanık riskleri",
        "Hammadde tozu, katkı maddesi ve kimyasal maruziyet",
        "Granül besleme, kırma ve konveyör sistemleri güvenliği",
        "Yangın yükü, duman ve uygun söndürme yöntemleri",
    ],
    "ahsap_mobilya": [
        "Testere, freze, planya ve CNC makinelerinde kesilme-kapılma",
        "Ahşap tozu maruziyeti, emiş sistemi ve toz patlaması",
        "Vernik, boya, tiner ve yapıştırıcılarla güvenli çalışma",
        "Zımpara, pres, çivi tabancası ve el aleti güvenliği",
        "Talaş-atık yönetimi, yangın önleme ve düzenli temizlik",
    ],
    "tekstil": [
        "Dokuma, örme, eğirme ve sarım makinelerine kapılma",
        "Tekstil tozu, lif, boya ve kimyasal maruziyet",
        "Kesim, dikim, ütü ve sıcak yüzey riskleri",
        "Gürültü, ergonomi ve tekrarlayan hareketler",
        "Yangın yükü, acil çıkış ve istif güvenliği",
    ],
    "gida_uretim": [
        "Kesici, kıyıcı, karıştırıcı ve konveyör makinelerinde güvenlik",
        "Sıcak proses, buhar, kızgın yağ ve yanık riskleri",
        "Soğuk depo, amonyak/CO2 kaçağı ve termal riskler",
        "Temizlik kimyasalları, CIP ve kaygan zemin riskleri",
        "Biyolojik etkenler, hijyen ve ergonomik taşıma riskleri",
    ],
    "kagit_matbaa": [
        "Kesim, baskı, sarım ve katlama makinelerinde kapılma",
        "Mürekkep, solvent ve temizlik kimyasallarıyla çalışma",
        "Kâğıt tozu, gürültü ve havalandırma",
        "Bobin, palet ve ağır malzeme taşıma güvenliği",
        "Yangın yükü, statik elektrik ve acil durumlar",
    ],
    "cam_seramik": [
        "Cam kırılması, keskin kenar ve göz yaralanmaları",
        "Fırın, sıcak ürün ve termal şok riskleri",
        "Silika, seramik tozu ve solunum korunması",
        "Pres, kesim, taşlama ve parça fırlaması riskleri",
        "Ağır plaka taşıma, vinç ve istifleme güvenliği",
    ],
    "cimento_beton": [
        "Çimento ve silika tozu maruziyeti",
        "Konveyör, kırıcı, mikser ve döner ekipmana kapılma",
        "Beton pompası, hortum savrulması ve basınç riskleri",
        "Mobil ekipman, saha trafiği ve kör noktalar",
        "Kimyasal katkı, alkalin yanık ve temizlik işlemleri",
    ],
    "elektronik": [
        "Lehim dumanı, flux ve kimyasal maruziyet",
        "Elektrik, statik elektrik ve hassas ekipman güvenliği",
        "Otomatik montaj hatlarında sıkışma ve robot riski",
        "Ergonomi, tekrarlayan iş ve ekranlı çalışma",
        "Batarya, test cihazı ve yangın riskleri",
    ],
    "ilac_kozmetik": [
        "Farmasötik toz ve aktif madde maruziyeti",
        "Solvent, dezenfektan ve laboratuvar kimyasalları",
        "Karıştırıcı, tabletleme ve dolum makinelerinde güvenlik",
        "Temiz oda, biyolojik risk ve hijyen prosedürleri",
        "Basınçlı sistem, sterilizasyon ve acil durumlar",
    ],
    "patlayici": [
        "Patlayıcı maddelerin özellikleri ve uyumsuzlukları",
        "Statik elektrik, kıvılcım ve ateşleme kaynaklarının kontrolü",
        "Üretim, dolum ve taşıma sırasında miktar-mesafe kuralları",
        "Patlayıcı depo, güvenlik mesafesi ve yıldırımdan korunma",
        "Acil durum, tahliye ve patlama sonrası müdahale",
    ],
    "genel_uretim": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "insaat": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "yol_asfalt": [
        "Trafik altında çalışma ve geçici trafik işaretlemesi",
        "Sıcak asfalt, bitüm sıçraması ve ısı stresi",
        "Finişer, silindir, freze ve iş makineleri güvenliği",
        "Bitüm dumanı, silika/toz ve gürültü maruziyeti",
        "Gece çalışması, görünürlük ve acil kaçış düzeni",
    ],
    "acik_maden": [
        "Şev, kademe, kaya düşmesi ve heyelan riskleri",
        "Patlatma operasyonu ve emniyet mesafeleri",
        "Kırma-eleme, konveyör ve sıkışma riskleri",
        "Toz, silika, gürültü ve titreşim maruziyeti",
        "Ocak içi trafik, iş makineleri ve kör noktalar",
    ],
    "kapali_maden": [
        "Grizu, metan ve patlayıcı ortam kontrolü",
        "Göçük, tahkimat ve yeraltı kazı güvenliği",
        "Havalandırma, gaz ölçümü ve oksijen yetersizliği",
        "Yeraltı nakliyatı, makine ve elektrik riskleri",
        "Kaçış, kurtarma, öz kurtarıcı ve acil durum planı",
    ],
    "petrol_dogalgaz": [
        "Yanıcı gaz-sıvı sızıntısı ve patlayıcı ortamlar",
        "Hidrojen sülfür, toksik gaz ve gaz ölçümü",
        "Tank, reaktör ve kapalı alanda çalışma",
        "Dolum-boşaltım, statik elektrik ve topraklama",
        "Sıcak çalışma, yangın ve acil durdurma sistemleri",
    ],
    "enerji_uretim": [
        "Yüksek gerilim, ark parlaması ve elektriksel izolasyon",
        "Türbin, jeneratör ve döner ekipman güvenliği",
        "Kazan, buhar, basınçlı sistem ve sıcak yüzeyler",
        "Bakımda kilitleme-etiketleme ve çalışma izinleri",
        "Yangın, kimyasal su şartlandırma ve acil durumlar",
    ],
    "yenilenebilir_enerji": [
        "Rüzgâr türbininde yüksekte çalışma ve kurtarma",
        "Güneş paneli DC gerilimi ve ark riski",
        "Kanat, kule, inverter ve mekanik bakım güvenliği",
        "Olumsuz hava, yıldırım ve uzak saha çalışması",
        "Enerji depolama bataryaları ve yangın riskleri",
    ],
    "elektrik_bakim": [
        "Elektrik çarpması ve ark parlaması",
        "Enerji kesme, doğrulama, kilitleme ve etiketleme",
        "Pano, kablo ve tesisat çalışmalarında güvenlik",
        "İzole ekipman, ölçü aleti ve uygun KKD kullanımı",
        "Yetkisiz müdahale, çalışma izni ve acil kurtarma",
    ],
    "telekom": [
        "Direk, kule ve çatıda yüksekte çalışma",
        "Elektrik, RF alanı ve enerji izolasyonu",
        "Saha trafiği, yol kenarı ve yalnız çalışma",
        "Fiber kablo, el aletleri ve göz yaralanmaları",
        "Olumsuz hava, erişim ve acil haberleşme",
    ],
    "depo_lojistik": [
        "Forklift, transpalet ve yaya trafiği güvenliği",
        "Raf sistemleri, istif ve yük düşmesi riskleri",
        "Yükleme rampası, dorse ve araç sabitleme",
        "Elle taşıma, kaldırma yardımcıları ve ergonomi",
        "Akü şarj alanı, yangın ve acil çıkış düzeni",
    ],
    "liman": [
        "Konteyner, vinç ve askıda yük operasyonları",
        "Araç-yaya trafiği ve terminal kör noktaları",
        "Rıhtımdan/sudan düşme ve kurtarma",
        "Tehlikeli yük, yakıt ve kimyasal sızıntılar",
        "Gemi-kara geçişi, hava koşulları ve acil durumlar",
    ],
    "tersane": [
        "Kapalı alan, gaz ölçümü ve tank çalışmaları",
        "Sıcak işler, kaynak, boya ve yangın riski",
        "Blok kaldırma, vinç ve askıda yük güvenliği",
        "İskele, gemi bordası ve yüksekte çalışma",
        "Basınçlı gaz, elektrik ve tahliye-kurtarma",
    ],
    "havacilik": [
        "Apron araç trafiği ve uçak çevresi güvenliği",
        "Jet blast, pervane ve hareketli yüzey tehlikeleri",
        "Yakıt ikmali, yangın ve statik elektrik",
        "Bagaj, kargo ve ergonomik yükleme riskleri",
        "Gürültü, hava koşulları ve acil durum prosedürleri",
    ],
    "demiryolu": [
        "Hat üzerinde çalışma ve tren çarpması riski",
        "Katener, üçüncü ray ve yüksek gerilim",
        "Makas, bakım makinesi ve sıkışma riskleri",
        "Tünel, istasyon ve tahliye güvenliği",
        "Gece çalışması, işaretleme ve haberleşme",
    ],
    "karayolu_tasimacilik": [
        "Güvenli sürüş, hız ve takip mesafesi",
        "Sürücü yorgunluğu, vardiya ve dikkat dağınıklığı",
        "Yük sabitleme, yükleme-boşaltma ve dorse güvenliği",
        "Araç bakımında kriko, lastik ve yol kenarı riskleri",
        "Trafik kazası, yangın ve acil durum prosedürleri",
    ],
    "kurye": [
        "Motosiklet/bisiklet sürüşü ve trafik riskleri",
        "Hava koşulları, görünürlük ve kişisel koruyucular",
        "Paket taşıma, ergonomi ve düşme riskleri",
        "Müşteri alanı, saldırı ve yalnız çalışma",
        "Araç bakım kontrolü ve acil haberleşme",
    ],
    "ofis": [
        "Ekranlı araçlar, oturma düzeni ve ergonomi",
        "Elektrikli ofis ekipmanlarının güvenli kullanımı",
        "Yangın, tahliye ve toplanma alanı uygulamaları",
        "Kayma, takılma, düşme ve düzen riskleri",
        "Psikososyal riskler, iş yükü ve stres yönetimi",
    ],
    "saglik": [
        "Biyolojik etkenler, enfeksiyon kontrolü ve izolasyon",
        "Kesici-delici yaralanmaları ve tıbbi atıklar",
        "Hasta taşıma, ergonomi ve şiddet riski",
        "İlaç, dezenfektan, sterilizasyon ve radyasyon riskleri",
        "Acil durum, tahliye ve güvenli sağlık hizmeti sunumu",
    ],
    "laboratuvar": [
        "Asit-baz, solvent ve reaktif kimyasal güvenliği",
        "Çeker ocak, havalandırma ve maruziyet kontrolü",
        "Basınçlı gaz tüpleri ve kriyojenik sıvılar",
        "Cam malzeme, kesici-delici ve biyolojik riskler",
        "Kimyasal atık, dökülme ve acil duş-göz duşu",
    ],
    "temizlik": [
        "Temizlik kimyasalları, etiket ve güvenli seyreltme",
        "Islak zemin, kayma ve düşme riskleri",
        "Biyolojik riskler, atıklar ve hijyen",
        "Yüksek alan temizliği ve merdiven güvenliği",
        "Kesici-delici atıklar, ergonomi ve KKD",
    ],
    "guvenlik": [
        "Şiddet, saldırı ve çatışma durumlarında güvenlik",
        "Devriye, yalnız çalışma ve haberleşme",
        "Yangın, tahliye ve kalabalık yönetimi",
        "Gece vardiyası, yorgunluk ve psikososyal riskler",
        "Şüpheli paket, acil olay ve kolluk koordinasyonu",
    ],
    "perakende": [
        "Müşteri ve çalışan alanlarında kayma-düşme",
        "Raf, istif ve malzeme düşmesi riskleri",
        "Depo, palet, transpalet ve elle taşıma",
        "Soğuk depo, kesici ekipman ve temizlik kimyasalları",
        "Yangın, acil çıkış ve kalabalık tahliyesi",
    ],
    "turizm": [
        "Mutfak, çamaşırhane, teknik servis ve sıcak yüzeyler",
        "Havuz kimyasalları ve biyolojik riskler",
        "Kat hizmetleri, ergonomi ve kayma-düşme",
        "Misafir güvenliği, şiddet ve gece vardiyası",
        "Yangın, kat tahliyesi ve acil durum yönetimi",
    ],
    "restoran": [
        "Bıçak, dilimleyici ve mutfak ekipmanları",
        "Kızgın yağ, buhar, fırın ve yanık riskleri",
        "LPG/doğalgaz, davlumbaz ve yangın güvenliği",
        "Kaygan zemin, temizlik kimyasalları ve hijyen",
        "Elle taşıma, ergonomi ve soğuk depo riskleri",
    ],
    "belediye": [
        "Saha, yol, park-bahçe ve trafik altında çalışma",
        "Atık toplama, biyolojik risk ve kesici-delici atıklar",
        "Kazı, altyapı, kanalizasyon ve kapalı alanlar",
        "İş makineleri, araçlar ve yaya güvenliği",
        "Halka açık alanlarda acil durum ve şiddet riski",
    ],
    "egitim_kurumu": [
        "Öğrenci, çalışan ve ziyaretçi güvenliği",
        "Laboratuvar, atölye ve spor alanı riskleri",
        "Yangın, deprem, tahliye ve toplanma alanları",
        "Elektrik, merdiven ve kayma-düşme riskleri",
        "Şiddet, psikososyal risk ve acil iletişim",
    ],
    "banka_finans": [
        "Ekranlı çalışma, ergonomi ve hareketsizlik",
        "İş stresi, müşteri baskısı ve psikososyal riskler",
        "Elektrik, yangın ve acil tahliye",
        "Güvenlik, saldırı ve nakit işlem riskleri",
        "Arşiv, depo ve kayma-takılma riskleri",
    ],
    "tarim": [
        "Traktör ve tarım makinelerinde devrilme-kapılma",
        "Pestisit, gübre ve kimyasal maruziyet",
        "Sıcaklık, güneş, biyolojik etken ve hayvan teması",
        "Sera, yüksekte çalışma ve elektrik riskleri",
        "Elle taşıma, ergonomi ve uzak saha acil durumları",
    ],
    "hayvancilik": [
        "Hayvan saldırısı, ezilme ve sıkışma riskleri",
        "Zoonozlar, biyolojik etkenler ve hijyen",
        "Gübre gazları, kapalı alan ve havalandırma",
        "Sağım, yemleme makineleri ve elektrik riskleri",
        "Ergonomi, kaygan zemin ve acil müdahale",
    ],
    "ormancilik": [
        "Motorlu testere, kesim ve ağaç devrilme yönü",
        "Arazi, eğim, kaya ve düşme riskleri",
        "Traktör, sürütme ve orman araçları güvenliği",
        "Yangın, sıcaklık, böcek ve biyolojik riskler",
        "Uzak saha, haberleşme, ilk yardım ve kurtarma",
    ],
    "atik_geri_donusum": [
        "Kesici-delici atıklar ve elle ayırma riskleri",
        "Pres, balya, kırıcı ve konveyör makineleri",
        "Biyolojik etken, toz, gaz ve koku maruziyeti",
        "Atık yangını, batarya ve kimyasal uyumsuzluk",
        "Araç trafiği, istif ve acil durum prosedürleri",
    ],
    "su_atiksu": [
        "Kanalizasyon gazları, oksijen yetersizliği ve kapalı alan",
        "Biyolojik etkenler, sıçrama ve hijyen",
        "Klor, ozon, asit-baz ve kimyasal dozlama",
        "Havuz, tank, düşme ve boğulma riskleri",
        "Pompa, elektrik, bakım ve enerji izolasyonu",
    ],
    "agac_isleri_marangozluk": [
        "Testere, freze, planya ve CNC makinelerinde kesilme-kapılma",
        "Ahşap tozu maruziyeti, emiş sistemi ve toz patlaması",
        "Vernik, boya, tiner ve yapıştırıcılarla güvenli çalışma",
        "Zımpara, pres, çivi tabancası ve el aleti güvenliği",
        "Talaş-atık yönetimi, yangın önleme ve düzenli temizlik",
    ],
    "ahsap_mobilya_uretimi": [
        "Testere, freze, planya ve CNC makinelerinde kesilme-kapılma",
        "Ahşap tozu maruziyeti, emiş sistemi ve toz patlaması",
        "Vernik, boya, tiner ve yapıştırıcılarla güvenli çalışma",
        "Zımpara, pres, çivi tabancası ve el aleti güvenliği",
        "Talaş-atık yönetimi, yangın önleme ve düzenli temizlik",
    ],
    "akaryakit_lpg_dolum_istasyonu": [
        "Yanıcı gaz-sıvı sızıntısı ve patlayıcı ortamlar",
        "Hidrojen sülfür, toksik gaz ve gaz ölçümü",
        "Tank, reaktör ve kapalı alanda çalışma",
        "Dolum-boşaltım, statik elektrik ve topraklama",
        "Sıcak çalışma, yangın ve acil durdurma sistemleri",
    ],
    "alisveris_merkezi_avm": [
        "Müşteri ve çalışan alanlarında kayma-düşme",
        "Raf, istif ve malzeme düşmesi riskleri",
        "Depo, palet, transpalet ve elle taşıma",
        "Soğuk depo, kesici ekipman ve temizlik kimyasalları",
        "Yangın, acil çıkış ve kalabalık tahliyesi",
    ],
    "aluminyum_profil_isleme": [
        "Kaynak ışını, göz-yüz koruması ve sıcak metal sıçraması",
        "Kaynak dumanı, gazlar ve lokal havalandırma",
        "Sıcak çalışma izni, kıvılcım kontrolü ve yangın gözcülüğü",
        "Basınçlı gaz tüpleri, regülatör ve hortum güvenliği",
        "Kapalı alanda kaynak, gaz ölçümü ve kurtarma planı",
    ],
    "ambalaj_paketleme": [
        "Kesim, baskı, sarım ve katlama makinelerinde kapılma",
        "Mürekkep, solvent ve temizlik kimyasallarıyla çalışma",
        "Kâğıt tozu, gürültü ve havalandırma",
        "Bobin, palet ve ağır malzeme taşıma güvenliği",
        "Yangın yükü, statik elektrik ve acil durumlar",
    ],
    "asansor_montaj_ve_bakim": [
        "Makine koruyucuları, emniyet tertibatları ve acil durdurma",
        "Kesilme, sıkışma, ezilme ve parça fırlaması riskleri",
        "Bakım ve ayarda enerji izolasyonu ile kilitleme-etiketleme",
        "Taşlama, kesme, matkap ve el aletleriyle güvenli çalışma",
        "Montaj, kaldırma-taşıma ve ergonomik zorlanmalar",
    ],
    "atik_yonetimi_geri_donusum": [
        "Kesici-delici atıklar ve elle ayırma riskleri",
        "Pres, balya, kırıcı ve konveyör makineleri",
        "Biyolojik etken, toz, gaz ve koku maruziyeti",
        "Atık yangını, batarya ve kimyasal uyumsuzluk",
        "Araç trafiği, istif ve acil durum prosedürleri",
    ],
    "avukatlik_hukuk_burosu": [
        "Kanalizasyon gazları, oksijen yetersizliği ve kapalı alan",
        "Biyolojik etkenler, sıçrama ve hijyen",
        "Klor, ozon, asit-baz ve kimyasal dozlama",
        "Havuz, tank, düşme ve boğulma riskleri",
        "Pompa, elektrik, bakım ve enerji izolasyonu",
    ],
    "ayakkabi_deri_uretimi": [
        "Dokuma, örme, eğirme ve sarım makinelerine kapılma",
        "Tekstil tozu, lif, boya ve kimyasal maruziyet",
        "Kesim, dikim, ütü ve sıcak yüzey riskleri",
        "Gürültü, ergonomi ve tekrarlayan hareketler",
        "Yangın yükü, acil çıkış ve istif güvenliği",
    ],
    "bakim_onarim_teknik_servis": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "balikcilik_su_urunleri": [
        "Kanalizasyon gazları, oksijen yetersizliği ve kapalı alan",
        "Biyolojik etkenler, sıçrama ve hijyen",
        "Klor, ozon, asit-baz ve kimyasal dozlama",
        "Havuz, tank, düşme ve boğulma riskleri",
        "Pompa, elektrik, bakım ve enerji izolasyonu",
    ],
    "banka_finans_2": [
        "Ekranlı çalışma, ergonomi ve hareketsizlik",
        "İş stresi, müşteri baskısı ve psikososyal riskler",
        "Elektrik, yangın ve acil tahliye",
        "Güvenlik, saldırı ve nakit işlem riskleri",
        "Arşiv, depo ve kayma-takılma riskleri",
    ],
    "basin_yayin_medya": [
        "Ekranlı araçlar, oturma düzeni ve ergonomi",
        "Elektrikli ofis ekipmanlarının güvenli kullanımı",
        "Yangın, tahliye ve toplanma alanı uygulamaları",
        "Kayma, takılma, düşme ve düzen riskleri",
        "Psikososyal riskler, iş yükü ve stres yönetimi",
    ],
    "belediye_kamu_hizmetleri": [
        "Saha, yol, park-bahçe ve trafik altında çalışma",
        "Atık toplama, biyolojik risk ve kesici-delici atıklar",
        "Kazı, altyapı, kanalizasyon ve kapalı alanlar",
        "İş makineleri, araçlar ve yaya güvenliği",
        "Halka açık alanlarda acil durum ve şiddet riski",
    ],
    "beton_cimento_hazir_beton": [
        "Çimento ve silika tozu maruziyeti",
        "Konveyör, kırıcı, mikser ve döner ekipmana kapılma",
        "Beton pompası, hortum savrulması ve basınç riskleri",
        "Mobil ekipman, saha trafiği ve kör noktalar",
        "Kimyasal katkı, alkalin yanık ve temizlik işlemleri",
    ],
    "bilisim_yazilim_it": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "boyahaneler_boya_uretimi": [
        "Kimyasal etiketler, SDS ve maruziyet yolları",
        "Solvent, izosiyanat, aerosol ve toksik buhar maruziyeti",
        "Yanıcı atmosfer, statik elektrik ve ex-proof ekipman",
        "Uyumsuz kimyasalların güvenli depolanması ve transferi",
        "Dökülme, sızıntı, acil duş ve müdahale prosedürleri",
    ],
    "cagri_merkezi_contact_center": [
        "Ekranlı çalışma, ergonomi ve hareketsizlik",
        "İş stresi, müşteri baskısı ve psikososyal riskler",
        "Elektrik, yangın ve acil tahliye",
        "Güvenlik, saldırı ve nakit işlem riskleri",
        "Arşiv, depo ve kayma-takılma riskleri",
    ],
    "cam_seramik_porselen": [
        "Cam kırılması, keskin kenar ve göz yaralanmaları",
        "Fırın, sıcak ürün ve termal şok riskleri",
        "Silika, seramik tozu ve solunum korunması",
        "Pres, kesim, taşlama ve parça fırlaması riskleri",
        "Ağır plaka taşıma, vinç ve istifleme güvenliği",
    ],
    "celik_yapi_metal_konstruksiyon": [
        "Kaynak ışını, göz-yüz koruması ve sıcak metal sıçraması",
        "Kaynak dumanı, gazlar ve lokal havalandırma",
        "Sıcak çalışma izni, kıvılcım kontrolü ve yangın gözcülüğü",
        "Basınçlı gaz tüpleri, regülatör ve hortum güvenliği",
        "Kapalı alanda kaynak, gaz ölçümü ve kurtarma planı",
    ],
    "cimento_klinker": [
        "Çimento ve silika tozu maruziyeti",
        "Konveyör, kırıcı, mikser ve döner ekipmana kapılma",
        "Beton pompası, hortum savrulması ve basınç riskleri",
        "Mobil ekipman, saha trafiği ve kör noktalar",
        "Kimyasal katkı, alkalin yanık ve temizlik işlemleri",
    ],
    "dagitim_kargo_kurye": [
        "Motosiklet/bisiklet sürüşü ve trafik riskleri",
        "Hava koşulları, görünürlük ve kişisel koruyucular",
        "Paket taşıma, ergonomi ve düşme riskleri",
        "Müşteri alanı, saldırı ve yalnız çalışma",
        "Araç bakım kontrolü ve acil haberleşme",
    ],
    "demir_celik_hadde": [
        "Ergimiş metal, cüruf ve sıcak yüzey sıçramaları",
        "Pota, vinç, kaldırma ve askı ekipmanı güvenliği",
        "Döküm dumanı, metal tozu, gaz ve havalandırma",
        "Isı stresi, yanıklar ve uygun KKD kullanımı",
        "Kalıp bozma, çapak alma ve sıkışma-ezilme riskleri",
    ],
    "depolama_lojistik_depo": [
        "Forklift, transpalet ve yaya trafiği güvenliği",
        "Raf sistemleri, istif ve yük düşmesi riskleri",
        "Yükleme rampası, dorse ve araç sabitleme",
        "Elle taşıma, kaldırma yardımcıları ve ergonomi",
        "Akü şarj alanı, yangın ve acil çıkış düzeni",
    ],
    "diger_belirtilmemis": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "dijital_baski_matbaa": [
        "Kesim, baskı, sarım ve katlama makinelerinde kapılma",
        "Mürekkep, solvent ve temizlik kimyasallarıyla çalışma",
        "Kâğıt tozu, gürültü ve havalandırma",
        "Bobin, palet ve ağır malzeme taşıma güvenliği",
        "Yangın yükü, statik elektrik ve acil durumlar",
    ],
    "dogalgaz_enerji_dagitim": [
        "Yanıcı gaz-sıvı sızıntısı ve patlayıcı ortamlar",
        "Hidrojen sülfür, toksik gaz ve gaz ölçümü",
        "Tank, reaktör ve kapalı alanda çalışma",
        "Dolum-boşaltım, statik elektrik ve topraklama",
        "Sıcak çalışma, yangın ve acil durdurma sistemleri",
    ],
    "e_ticaret_depo_fulfillment": [
        "Forklift, transpalet ve yaya trafiği güvenliği",
        "Raf sistemleri, istif ve yük düşmesi riskleri",
        "Yükleme rampası, dorse ve araç sabitleme",
        "Elle taşıma, kaldırma yardımcıları ve ergonomi",
        "Akü şarj alanı, yangın ve acil çıkış düzeni",
    ],
    "eczane_medikal_satis": [
        "Biyolojik etkenler, enfeksiyon kontrolü ve izolasyon",
        "Kesici-delici yaralanmaları ve tıbbi atıklar",
        "Hasta taşıma, ergonomi ve şiddet riski",
        "İlaç, dezenfektan, sterilizasyon ve radyasyon riskleri",
        "Acil durum, tahliye ve güvenli sağlık hizmeti sunumu",
    ],
    "egitim_okul_kurs": [
        "Öğrenci, çalışan ve ziyaretçi güvenliği",
        "Laboratuvar, atölye ve spor alanı riskleri",
        "Yangın, deprem, tahliye ve toplanma alanları",
        "Elektrik, merdiven ve kayma-düşme riskleri",
        "Şiddet, psikososyal risk ve acil iletişim",
    ],
    "elektrik_elektronik_uretim": [
        "Lehim dumanı, flux ve kimyasal maruziyet",
        "Elektrik, statik elektrik ve hassas ekipman güvenliği",
        "Otomatik montaj hatlarında sıkışma ve robot riski",
        "Ergonomi, tekrarlayan iş ve ekranlı çalışma",
        "Batarya, test cihazı ve yangın riskleri",
    ],
    "elektrik_tesisat_pano_montaj": [
        "Elektrik çarpması ve ark parlaması",
        "Enerji kesme, doğrulama, kilitleme ve etiketleme",
        "Pano, kablo ve tesisat çalışmalarında güvenlik",
        "İzole ekipman, ölçü aleti ve uygun KKD kullanımı",
        "Yetkisiz müdahale, çalışma izni ve acil kurtarma",
    ],
    "elektronik_atik_bertaraf": [
        "Lehim dumanı, flux ve kimyasal maruziyet",
        "Elektrik, statik elektrik ve hassas ekipman güvenliği",
        "Otomatik montaj hatlarında sıkışma ve robot riski",
        "Ergonomi, tekrarlayan iş ve ekranlı çalışma",
        "Batarya, test cihazı ve yangın riskleri",
    ],
    "enerji_jenerator_trafo": [
        "Yüksek gerilim, ark parlaması ve elektriksel izolasyon",
        "Türbin, jeneratör ve döner ekipman güvenliği",
        "Kazan, buhar, basınçlı sistem ve sıcak yüzeyler",
        "Bakımda kilitleme-etiketleme ve çalışma izinleri",
        "Yangın, kimyasal su şartlandırma ve acil durumlar",
    ],
    "fabrika_genel_imalat": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "firin_unlu_mamuller": [
        "Kesici, kıyıcı, karıştırıcı ve konveyör makinelerinde güvenlik",
        "Sıcak proses, buhar, kızgın yağ ve yanık riskleri",
        "Soğuk depo, amonyak/CO2 kaçağı ve termal riskler",
        "Temizlik kimyasalları, CIP ve kaygan zemin riskleri",
        "Biyolojik etkenler, hijyen ve ergonomik taşıma riskleri",
    ],
    "gemi_insa_tersane": [
        "Konteyner, vinç ve askıda yük operasyonları",
        "Araç-yaya trafiği ve terminal kör noktaları",
        "Rıhtımdan/sudan düşme ve kurtarma",
        "Tehlikeli yük, yakıt ve kimyasal sızıntılar",
        "Gemi-kara geçişi, hava koşulları ve acil durumlar",
    ],
    "gida_uretimi_isleme": [
        "Kesici, kıyıcı, karıştırıcı ve konveyör makinelerinde güvenlik",
        "Sıcak proses, buhar, kızgın yağ ve yanık riskleri",
        "Soğuk depo, amonyak/CO2 kaçağı ve termal riskler",
        "Temizlik kimyasalları, CIP ve kaygan zemin riskleri",
        "Biyolojik etkenler, hijyen ve ergonomik taşıma riskleri",
    ],
    "guvenlik_hizmetleri": [
        "Şiddet, saldırı ve çatışma durumlarında güvenlik",
        "Devriye, yalnız çalışma ve haberleşme",
        "Yangın, tahliye ve kalabalık yönetimi",
        "Gece vardiyası, yorgunluk ve psikososyal riskler",
        "Şüpheli paket, acil olay ve kolluk koordinasyonu",
    ],
    "guzellik_kuafor_spa": [
        "Bıçak, dilimleyici ve mutfak ekipmanları",
        "Kızgın yağ, buhar, fırın ve yanık riskleri",
        "LPG/doğalgaz, davlumbaz ve yangın güvenliği",
        "Kaygan zemin, temizlik kimyasalları ve hijyen",
        "Elle taşıma, ergonomi ve soğuk depo riskleri",
    ],
    "haberlesme_telekomunikasyon": [
        "Direk, kule ve çatıda yüksekte çalışma",
        "Elektrik, RF alanı ve enerji izolasyonu",
        "Saha trafiği, yol kenarı ve yalnız çalışma",
        "Fiber kablo, el aletleri ve göz yaralanmaları",
        "Olumsuz hava, erişim ve acil haberleşme",
    ],
    "havalimani_yer_hizmetleri": [
        "Konteyner, vinç ve askıda yük operasyonları",
        "Araç-yaya trafiği ve terminal kör noktaları",
        "Rıhtımdan/sudan düşme ve kurtarma",
        "Tehlikeli yük, yakıt ve kimyasal sızıntılar",
        "Gemi-kara geçişi, hava koşulları ve acil durumlar",
    ],
    "hayvancilik_ciftlik": [
        "Hayvan saldırısı, ezilme ve sıkışma riskleri",
        "Zoonozlar, biyolojik etkenler ve hijyen",
        "Gübre gazları, kapalı alan ve havalandırma",
        "Sağım, yemleme makineleri ve elektrik riskleri",
        "Ergonomi, kaygan zemin ve acil müdahale",
    ],
    "hazir_giyim_konfeksiyon": [
        "Dokuma, örme, eğirme ve sarım makinelerine kapılma",
        "Tekstil tozu, lif, boya ve kimyasal maruziyet",
        "Kesim, dikim, ütü ve sıcak yüzey riskleri",
        "Gürültü, ergonomi ve tekrarlayan hareketler",
        "Yangın yükü, acil çıkış ve istif güvenliği",
    ],
    "hirdavat_yapi_market": [
        "Müşteri ve çalışan alanlarında kayma-düşme",
        "Raf, istif ve malzeme düşmesi riskleri",
        "Depo, palet, transpalet ve elle taşıma",
        "Soğuk depo, kesici ekipman ve temizlik kimyasalları",
        "Yangın, acil çıkış ve kalabalık tahliyesi",
    ],
    "ic_mimarlik_dekorasyon": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "ilac_farmasotik_uretim": [
        "Farmasötik toz ve aktif madde maruziyeti",
        "Solvent, dezenfektan ve laboratuvar kimyasalları",
        "Karıştırıcı, tabletleme ve dolum makinelerinde güvenlik",
        "Temiz oda, biyolojik risk ve hijyen prosedürleri",
        "Basınçlı sistem, sterilizasyon ve acil durumlar",
    ],
    "insaat_santiye": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "is_makinesi_agir_ekipman": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "iskele_kalip_yapi_ekipmani": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "kablo_tel_uretimi": [
        "Lehim dumanı, flux ve kimyasal maruziyet",
        "Elektrik, statik elektrik ve hassas ekipman güvenliği",
        "Otomatik montaj hatlarında sıkışma ve robot riski",
        "Ergonomi, tekrarlayan iş ve ekranlı çalışma",
        "Batarya, test cihazı ve yangın riskleri",
    ],
    "kagit_karton_uretimi": [
        "Kesim, baskı, sarım ve katlama makinelerinde kapılma",
        "Mürekkep, solvent ve temizlik kimyasallarıyla çalışma",
        "Kâğıt tozu, gürültü ve havalandırma",
        "Bobin, palet ve ağır malzeme taşıma güvenliği",
        "Yangın yükü, statik elektrik ve acil durumlar",
    ],
    "kamu_kurumu_idare": [
        "Saha, yol, park-bahçe ve trafik altında çalışma",
        "Atık toplama, biyolojik risk ve kesici-delici atıklar",
        "Kazı, altyapı, kanalizasyon ve kapalı alanlar",
        "İş makineleri, araçlar ve yaya güvenliği",
        "Halka açık alanlarda acil durum ve şiddet riski",
    ],
    "kimya_kimyasal_uretim": [
        "Kimyasal etiketler, SDS ve maruziyet yolları",
        "Solvent, izosiyanat, aerosol ve toksik buhar maruziyeti",
        "Yanıcı atmosfer, statik elektrik ve ex-proof ekipman",
        "Uyumsuz kimyasalların güvenli depolanması ve transferi",
        "Dökülme, sızıntı, acil duş ve müdahale prosedürleri",
    ],
    "konaklama_otel_pansiyon": [
        "Mutfak, çamaşırhane, teknik servis ve sıcak yüzeyler",
        "Havuz kimyasalları ve biyolojik riskler",
        "Kat hizmetleri, ergonomi ve kayma-düşme",
        "Misafir güvenliği, şiddet ve gece vardiyası",
        "Yangın, kat tahliyesi ve acil durum yönetimi",
    ],
    "kozmetik_temizlik_urunleri": [
        "Farmasötik toz ve aktif madde maruziyeti",
        "Solvent, dezenfektan ve laboratuvar kimyasalları",
        "Karıştırıcı, tabletleme ve dolum makinelerinde güvenlik",
        "Temiz oda, biyolojik risk ve hijyen prosedürleri",
        "Basınçlı sistem, sterilizasyon ve acil durumlar",
    ],
    "kuyumculuk_mucevher": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "laboratuvar_analiz": [
        "Asit-baz, solvent ve reaktif kimyasal güvenliği",
        "Çeker ocak, havalandırma ve maruziyet kontrolü",
        "Basınçlı gaz tüpleri ve kriyojenik sıvılar",
        "Cam malzeme, kesici-delici ve biyolojik riskler",
        "Kimyasal atık, dökülme ve acil duş-göz duşu",
    ],
    "lastik_kaucuk": [
        "Enjeksiyon, ekstrüzyon ve pres makinelerinde sıkışma",
        "Sıcak kalıp, eriyik polimer ve yanık riskleri",
        "Hammadde tozu, katkı maddesi ve kimyasal maruziyet",
        "Granül besleme, kırma ve konveyör sistemleri güvenliği",
        "Yangın yükü, duman ve uygun söndürme yöntemleri",
    ],
    "madencilik_maden_ocagi": [
        "Şev, kademe, kaya düşmesi ve heyelan riskleri",
        "Patlatma operasyonu ve emniyet mesafeleri",
        "Kırma-eleme, konveyör ve sıkışma riskleri",
        "Toz, silika, gürültü ve titreşim maruziyeti",
        "Ocak içi trafik, iş makineleri ve kör noktalar",
    ],
    "makine_imalati": [
        "Makine koruyucuları, emniyet tertibatları ve acil durdurma",
        "Kesilme, sıkışma, ezilme ve parça fırlaması riskleri",
        "Bakım ve ayarda enerji izolasyonu ile kilitleme-etiketleme",
        "Taşlama, kesme, matkap ve el aletleriyle güvenli çalışma",
        "Montaj, kaldırma-taşıma ve ergonomik zorlanmalar",
    ],
    "market_perakende": [
        "Müşteri ve çalışan alanlarında kayma-düşme",
        "Raf, istif ve malzeme düşmesi riskleri",
        "Depo, palet, transpalet ve elle taşıma",
        "Soğuk depo, kesici ekipman ve temizlik kimyasalları",
        "Yangın, acil çıkış ve kalabalık tahliyesi",
    ],
    "metal_isleme_torna_freze": [
        "Makine koruyucuları, emniyet tertibatları ve acil durdurma",
        "Kesilme, sıkışma, ezilme ve parça fırlaması riskleri",
        "Bakım ve ayarda enerji izolasyonu ile kilitleme-etiketleme",
        "Taşlama, kesme, matkap ve el aletleriyle güvenli çalışma",
        "Montaj, kaldırma-taşıma ve ergonomik zorlanmalar",
    ],
    "metal_yapi_elemanlari_toptan": [
        "Uzun ve ağır metal yapı elemanlarının vinç, forklift ve uygun kaldırma aparatlarıyla güvenli yüklenmesi",
        "Konstrüksiyon elemanlarının devrilmeye ve kaymaya karşı takozlanması, bağlanması ve güvenli istiflenmesi",
        "Keskin kenarlar, çapaklar, sıkışma ve ezilmelere karşı el-göz-ayak koruması",
        "Araç-yaya yolları, yükleme sahası, dorse yanaşması ve kör nokta güvenliği",
        "Açık saha depolaması, hava koşulları, yük sabitleme ve sevkiyat öncesi kontroller",
    ],
    "ticaret_aracilik_ofis": [
        "Müşteri ve tedarikçi ziyaretlerinde yol, saha ve yalnız çalışma güvenliği",
        "Numune, katalog ve hafif yüklerin ergonomik taşınması",
        "Ekranlı araçlar, oturma düzeni ve ofis ergonomisi",
        "Ziyaret edilen işyerlerinin kurallarına uyum ve tehlikeli alana izinsiz girmeme",
        "Yangın, tahliye, şiddet, psikososyal riskler ve acil haberleşme",
    ],
    "tarimsal_urun_toptan": [
        "Tahıl, tohum ve yemlerde toz, küf, haşere ve biyolojik maruziyetlerin kontrolü",
        "Dökme ve çuvallı ürünlerin güvenli istifi, silo ve çökme-gömülme riskleri",
        "Forklift, yükleyici, konveyör ve araç-yaya trafiği güvenliği",
        "Çuval ve balyaların mekanik yardımcılarla taşınması ve ergonomi",
        "Yanıcı toz, yangın, fumigasyon ve acil durum uygulamaları",
    ],
    "canli_hayvan_toptan": [
        "Hayvan tekmesi, boynuz darbesi, ısırma ve sıkışmaya karşı güvenli sevk-idare",
        "Zoonozlar, karantina, hijyen ve biyolojik etkenlerden korunma",
        "Padok, kafes, rampa ve bariyerlerin güvenli kullanımı",
        "Canlı hayvan yükleme, boşaltma ve taşıma sırasında araç güvenliği",
        "Hayvan kaçması, çalışan yaralanması ve diğer acil durumlara müdahale",
    ],
    "gida_toptan_depo": [
        "Soğuk zincir, ürün sıcaklığı ve soğuk depo çalışma güvenliği",
        "Gıda hijyeni, çapraz bulaşma, haşere kontrolü ve temizlik",
        "Palet, raf ve istif güvenliği ile forklift-yaya yollarının ayrılması",
        "Kasa, çuval ve kolilerin mekanik yardımcılarla ergonomik taşınması",
        "Yükleme rampası, sevkiyat aracı, yangın ve soğutucu akışkan acil durumları",
    ],
    "tekstil_deri_toptan": [
        "Rulo, balya, koli ve askılı ürünlerin devrilmeye karşı güvenli istiflenmesi",
        "Yüksek yangın yükü, sigara ve ateşleme kaynaklarının kontrolü",
        "Forklift, transpalet ve yükleme alanında araç-yaya güvenliği",
        "Rulo ve kolilerin ergonomik taşınması; kesici ambalaj aletlerinin güvenli kullanımı",
        "Nem, küf, kimyasal kalıntı, tahliye ve acil durum düzeni",
    ],
    "elektrik_elektronik_toptan": [
        "Elektrikli ürünlerin hasar, kaçak ve güvenli demo/enerjilendirme kontrolleri",
        "Pil, batarya ve akümülatörlerin kısa devre, ısınma ve yangına karşı depolanması",
        "Hassas ve ağır cihazların düşmeye karşı güvenli istifi ve taşınması",
        "Forklift, transpalet, yükleme alanı ve araç-yaya trafiği güvenliği",
        "Elektronik atık, yangın, tahliye ve enerji kesme uygulamaları",
    ],
    "kimyasal_toptan_depo": [
        "Etiket ve güvenlik bilgi formuna göre kimyasal kabulü, depolama ve sevkiyat",
        "Uyumsuz kimyasalların ayrılması, ikincil kaplama ve havalandırma",
        "Yanıcı, oksitleyici, aşındırıcı ve toksik ürünlerde yangın-patlama kontrolü",
        "Dökülme-sızıntı müdahalesi, göz duşu, acil duş ve uygun kişisel koruyucular",
        "Tanker, varil ve IBC yükleme-boşaltma; araç, forklift ve statik elektrik güvenliği",
    ],
    "ecza_medikal_toptan": [
        "İlaç ve medikal ürünlerde sıcaklık, nem, soğuk zincir ve izlenebilirlik",
        "Steril, kontrollü ve hassas ürünlerin ayrılmış ve güvenli depolanması",
        "Raf, palet, koli ve cihazların devrilmeye karşı güvenli istifi",
        "Forklift, transpalet, yükleme alanı ve ergonomik taşıma güvenliği",
        "Kırılma, dökülme, kesici-delici ürün, yangın ve acil durum yönetimi",
    ],
    "mobilya_ev_esyasi_toptan": [
        "Büyük hacimli mobilya, cam ve ev eşyalarının devrilmeye karşı sabitlenmesi",
        "Forklift, kaldırma aparatı, yükleme rampası ve araç-yaya trafiği güvenliği",
        "Cam, seramik, keskin kenar ve kırılmaya karşı el-göz-ayak koruması",
        "Ağır ve hacimli yüklerin ekip halinde veya mekanik yardımcıyla taşınması",
        "Ahşap, ambalaj ve tekstil kaynaklı yangın yükü ile tahliye düzeni",
    ],
    "makine_ekipman_toptan": [
        "Ağır makine ve parçaların kapasiteye uygun ekipmanla kaldırılması ve yüklenmesi",
        "Makine, aparat ve yedek parçaların devrilmeye karşı takozlanması ve sabitlenmesi",
        "Demo, test ve teslimatta enerji izolasyonu, koruyucu ve yetkisiz çalıştırma kontrolü",
        "Keskin kenar, sıkışma, ezilme ve hidrolik-basınçlı sistem riskleri",
        "Forklift, vinç, araç-yaya trafiği, sevkiyat ve acil durum güvenliği",
    ],
    "otomotiv_toptan": [
        "Araç hareketi, manevra, park ve yaya yollarında çarpışmanın önlenmesi",
        "Araç ve parçaların yükleme, indirme, bağlama ve sevkiyat güvenliği",
        "Akü, yakıt, yağ ve diğer kimyasallarda yangın-dökülme kontrolü",
        "Lastik, motor ve ağır parçaların güvenli istifi ve ergonomik taşınması",
        "Hasarlı araç, elektrikli araç yüksek gerilimi ve acil durum uygulamaları",
    ],
    "yakit_toptan_depo": [
        "Yanıcı ve parlayıcı yakıtların tank, tüp ve ambalajlarda güvenli depolanması",
        "Dolum-boşaltımda statik elektrik, topraklama ve ateşleme kaynaklarının kontrolü",
        "Tanker ve tüp araçlarında yanaşma, hortum bağlantısı ve araç sabitleme",
        "Gaz algılama, havalandırma, sızıntı-dökülme ve uygun kişisel koruyucular",
        "Yangın, patlama, tahliye ve acil durum müdahale planı",
    ],
    "yapi_malzemeleri_toptan": [
        "Uzun, ağır ve hacimli yapı malzemelerinin güvenli kaldırılması ve yüklenmesi",
        "Levha, boru, profil, palet ve blokların devrilmeye karşı takozlanması ve istifi",
        "Keskin kenar, kırılma, ezilme ve mineral tozlarına karşı korunma",
        "Forklift, vinç, açık saha ve araç-yaya trafiği güvenliği",
        "Yük sabitleme, hava koşulları, yangın ve sevkiyat öncesi kontroller",
    ],
    "atik_hurda_toptan": [
        "Kaynağı belirsiz atık ve hurdaların kabulü, tanımlanması ve tehlikeli atıktan ayrılması",
        "Keskin kenar, iğne, metal çapak ve biyolojik-kimyasal kalıntılardan korunma",
        "Hurda yığınlarının çökme-devrilme riski ve güvenli istiflenmesi",
        "Kepçe, vinç, pres, forklift ve ağır araçlarla çalışma güvenliği",
        "Akü, gaz tüpü, yanıcı atık, yangın-patlama ve acil durum yönetimi",
    ],
    "genel_toptan_depo": [
        "Ürün özelliğine göre kabul, etiketleme, ayrıştırma ve güvenli depolama",
        "Raf, palet ve istiflerin kapasite, devrilme ve yük düşmesi kontrolleri",
        "Forklift, transpalet, yükleme rampası ve araç-yaya trafiği güvenliği",
        "Elle taşıma, mekanik yardımcılar, kesici ambalaj aletleri ve ergonomi",
        "Yangın yükü, acil çıkış, dökülme ve sevkiyat öncesi kontroller",
    ],
    "kimyasal_perakende": [
        "Etiket ve güvenlik bilgi formuna göre kimyasal ürünlerin güvenli satışı ve depolanması",
        "Yanıcı, aşındırıcı, toksik ve oksitleyici ürünlerin uyumlu biçimde ayrılması",
        "Ambalaj hasarı, dökülme, sızıntı ve müşteri maruziyetinin önlenmesi",
        "Havalandırma, ateşleme kaynakları, uygun kişisel koruyucu ve hijyen",
        "Yangın, tahliye, dökülme kiti ve acil durum uygulamaları",
    ],
    "mobilya_ev_tekstili": [
        "Testere, freze, planya ve CNC makinelerinde kesilme-kapılma",
        "Ahşap tozu maruziyeti, emiş sistemi ve toz patlaması",
        "Vernik, boya, tiner ve yapıştırıcılarla güvenli çalışma",
        "Zımpara, pres, çivi tabancası ve el aleti güvenliği",
        "Talaş-atık yönetimi, yangın önleme ve düzenli temizlik",
    ],
    "muhendislik_proje_ofisi": [
        "Ekranlı araçlar, oturma düzeni ve ergonomi",
        "Elektrikli ofis ekipmanlarının güvenli kullanımı",
        "Yangın, tahliye ve toplanma alanı uygulamaları",
        "Kayma, takılma, düşme ve düzen riskleri",
        "Psikososyal riskler, iş yükü ve stres yönetimi",
    ],
    "muteahhitlik_taahhut": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "nakliye_karayolu_tasimaciligi": [
        "Trafik altında çalışma ve geçici trafik işaretlemesi",
        "Sıcak asfalt, bitüm sıçraması ve ısı stresi",
        "Finişer, silindir, freze ve iş makineleri güvenliği",
        "Bitüm dumanı, silika/toz ve gürültü maruziyeti",
        "Gece çalışması, görünürlük ve acil kaçış düzeni",
    ],
    "ofis_idari_hizmetler": [
        "Ekranlı araçlar, oturma düzeni ve ergonomi",
        "Elektrikli ofis ekipmanlarının güvenli kullanımı",
        "Yangın, tahliye ve toplanma alanı uygulamaları",
        "Kayma, takılma, düşme ve düzen riskleri",
        "Psikososyal riskler, iş yükü ve stres yönetimi",
    ],
    "organizasyon_etkinlik": [
        "Ekranlı araçlar, oturma düzeni ve ergonomi",
        "Elektrikli ofis ekipmanlarının güvenli kullanımı",
        "Yangın, tahliye ve toplanma alanı uygulamaları",
        "Kayma, takılma, düşme ve düzen riskleri",
        "Psikososyal riskler, iş yükü ve stres yönetimi",
    ],
    "ormancilik_kereste": [
        "Motorlu testere, kesim ve ağaç devrilme yönü",
        "Arazi, eğim, kaya ve düşme riskleri",
        "Traktör, sürütme ve orman araçları güvenliği",
        "Yangın, sıcaklık, böcek ve biyolojik riskler",
        "Uzak saha, haberleşme, ilk yardım ve kurtarma",
    ],
    "oto_lastik_servis": [
        "Pres, robotlu hücre ve hareketli hatlarda sıkışma riskleri",
        "Araç lifti, kriko ve bakım çukuru güvenliği",
        "Boya, solvent, kaynak dumanı ve kimyasal maruziyet",
        "Akü sökme-takma ve elektrikli araç yüksek gerilim riskleri",
        "Trafik, test sürüşü ve ergonomik montaj riskleri",
    ],
    "otogaz_lpg_bayi": [
        "Yanıcı gaz-sıvı sızıntısı ve patlayıcı ortamlar",
        "Hidrojen sülfür, toksik gaz ve gaz ölçümü",
        "Tank, reaktör ve kapalı alanda çalışma",
        "Dolum-boşaltım, statik elektrik ve topraklama",
        "Sıcak çalışma, yangın ve acil durdurma sistemleri",
    ],
    "otomotiv_servis_bakim": [
        "Pres, robotlu hücre ve hareketli hatlarda sıkışma riskleri",
        "Araç lifti, kriko ve bakım çukuru güvenliği",
        "Boya, solvent, kaynak dumanı ve kimyasal maruziyet",
        "Akü sökme-takma ve elektrikli araç yüksek gerilim riskleri",
        "Trafik, test sürüşü ve ergonomik montaj riskleri",
    ],
    "otomotiv_yedek_parca": [
        "Pres, robotlu hücre ve hareketli hatlarda sıkışma riskleri",
        "Araç lifti, kriko ve bakım çukuru güvenliği",
        "Boya, solvent, kaynak dumanı ve kimyasal maruziyet",
        "Akü sökme-takma ve elektrikli araç yüksek gerilim riskleri",
        "Trafik, test sürüşü ve ergonomik montaj riskleri",
    ],
    "ozel_guvenlik": [
        "Şiddet, saldırı ve çatışma durumlarında güvenlik",
        "Devriye, yalnız çalışma ve haberleşme",
        "Yangın, tahliye ve kalabalık yönetimi",
        "Gece vardiyası, yorgunluk ve psikososyal riskler",
        "Şüpheli paket, acil olay ve kolluk koordinasyonu",
    ],
    "petrol_rafineri_depolama": [
        "Yanıcı gaz-sıvı sızıntısı ve patlayıcı ortamlar",
        "Hidrojen sülfür, toksik gaz ve gaz ölçümü",
        "Tank, reaktör ve kapalı alanda çalışma",
        "Dolum-boşaltım, statik elektrik ve topraklama",
        "Sıcak çalışma, yangın ve acil durdurma sistemleri",
    ],
    "plastik_enjeksiyon_ekstruzyon": [
        "Enjeksiyon, ekstrüzyon ve pres makinelerinde sıkışma",
        "Sıcak kalıp, eriyik polimer ve yanık riskleri",
        "Hammadde tozu, katkı maddesi ve kimyasal maruziyet",
        "Granül besleme, kırma ve konveyör sistemleri güvenliği",
        "Yangın yükü, duman ve uygun söndürme yöntemleri",
    ],
    "reklam_tabela_baski": [
        "Kesim, baskı, sarım ve katlama makinelerinde kapılma",
        "Mürekkep, solvent ve temizlik kimyasallarıyla çalışma",
        "Kâğıt tozu, gürültü ve havalandırma",
        "Bobin, palet ve ağır malzeme taşıma güvenliği",
        "Yangın yükü, statik elektrik ve acil durumlar",
    ],
    "restoran_cafe_mutfak": [
        "Bıçak, dilimleyici ve mutfak ekipmanları",
        "Kızgın yağ, buhar, fırın ve yanık riskleri",
        "LPG/doğalgaz, davlumbaz ve yangın güvenliği",
        "Kaygan zemin, temizlik kimyasalları ve hijyen",
        "Elle taşıma, ergonomi ve soğuk depo riskleri",
    ],
    "saglik_hastane_klinik": [
        "Biyolojik etkenler, enfeksiyon kontrolü ve izolasyon",
        "Kesici-delici yaralanmaları ve tıbbi atıklar",
        "Hasta taşıma, ergonomi ve şiddet riski",
        "İlaç, dezenfektan, sterilizasyon ve radyasyon riskleri",
        "Acil durum, tahliye ve güvenli sağlık hizmeti sunumu",
    ],
    "seramik_fayans": [
        "Cam kırılması, keskin kenar ve göz yaralanmaları",
        "Fırın, sıcak ürün ve termal şok riskleri",
        "Silika, seramik tozu ve solunum korunması",
        "Pres, kesim, taşlama ve parça fırlaması riskleri",
        "Ağır plaka taşıma, vinç ve istifleme güvenliği",
    ],
    "sigorta_broker": [
        "Ekranlı çalışma, ergonomi ve hareketsizlik",
        "İş stresi, müşteri baskısı ve psikososyal riskler",
        "Elektrik, yangın ve acil tahliye",
        "Güvenlik, saldırı ve nakit işlem riskleri",
        "Arşiv, depo ve kayma-takılma riskleri",
    ],
    "soguk_hava_deposu": [
        "Forklift, transpalet ve yaya trafiği güvenliği",
        "Raf sistemleri, istif ve yük düşmesi riskleri",
        "Yükleme rampası, dorse ve araç sabitleme",
        "Elle taşıma, kaldırma yardımcıları ve ergonomi",
        "Akü şarj alanı, yangın ve acil çıkış düzeni",
    ],
    "spor_tesisi_fitness": [
        "Mutfak, çamaşırhane, teknik servis ve sıcak yüzeyler",
        "Havuz kimyasalları ve biyolojik riskler",
        "Kat hizmetleri, ergonomi ve kayma-düşme",
        "Misafir güvenliği, şiddet ve gece vardiyası",
        "Yangın, kat tahliyesi ve acil durum yönetimi",
    ],
    "sut_sut_urunleri": [
        "Kesici, kıyıcı, karıştırıcı ve konveyör makinelerinde güvenlik",
        "Sıcak proses, buhar, kızgın yağ ve yanık riskleri",
        "Soğuk depo, amonyak/CO2 kaçağı ve termal riskler",
        "Temizlik kimyasalları, CIP ve kaygan zemin riskleri",
        "Biyolojik etkenler, hijyen ve ergonomik taşıma riskleri",
    ],
    "tarim_ziraat": [
        "Traktör ve tarım makinelerinde devrilme-kapılma",
        "Pestisit, gübre ve kimyasal maruziyet",
        "Sıcaklık, güneş, biyolojik etken ve hayvan teması",
        "Sera, yüksekte çalışma ve elektrik riskleri",
        "Elle taşıma, ergonomi ve uzak saha acil durumları",
    ],
    "tas_ocagi_maden_ocagi": [
        "Şev, kademe, kaya düşmesi ve heyelan riskleri",
        "Patlatma operasyonu ve emniyet mesafeleri",
        "Kırma-eleme, konveyör ve sıkışma riskleri",
        "Toz, silika, gürültü ve titreşim maruziyeti",
        "Ocak içi trafik, iş makineleri ve kör noktalar",
    ],
    "tekstil_dokuma_boyama": [
        "Ergimiş metal, cüruf ve sıcak yüzey sıçramaları",
        "Pota, vinç, kaldırma ve askı ekipmanı güvenliği",
        "Döküm dumanı, metal tozu, gaz ve havalandırma",
        "Isı stresi, yanıklar ve uygun KKD kullanımı",
        "Kalıp bozma, çapak alma ve sıkışma-ezilme riskleri",
    ],
    "telekomunikasyon_altyapi": [
        "Direk, kule ve çatıda yüksekte çalışma",
        "Elektrik, RF alanı ve enerji izolasyonu",
        "Saha trafiği, yol kenarı ve yalnız çalışma",
        "Fiber kablo, el aletleri ve göz yaralanmaları",
        "Olumsuz hava, erişim ve acil haberleşme",
    ],
    "temizlik_facility_management": [
        "Temizlik kimyasalları, etiket ve güvenli seyreltme",
        "Islak zemin, kayma ve düşme riskleri",
        "Biyolojik riskler, atıklar ve hijyen",
        "Yüksek alan temizliği ve merdiven güvenliği",
        "Kesici-delici atıklar, ergonomi ve KKD",
    ],
    "tersane_liman_hizmetleri": [
        "Konteyner, vinç ve askıda yük operasyonları",
        "Araç-yaya trafiği ve terminal kör noktaları",
        "Rıhtımdan/sudan düşme ve kurtarma",
        "Tehlikeli yük, yakıt ve kimyasal sızıntılar",
        "Gemi-kara geçişi, hava koşulları ve acil durumlar",
    ],
    "tip_dis_klinigi": [
        "Biyolojik etkenler, enfeksiyon kontrolü ve izolasyon",
        "Kesici-delici yaralanmaları ve tıbbi atıklar",
        "Hasta taşıma, ergonomi ve şiddet riski",
        "İlaç, dezenfektan, sterilizasyon ve radyasyon riskleri",
        "Acil durum, tahliye ve güvenli sağlık hizmeti sunumu",
    ],
    "toplu_tasima_ulasim": [
        "Güvenli sürüş, hız ve takip mesafesi",
        "Sürücü yorgunluğu, vardiya ve dikkat dağınıklığı",
        "Yük sabitleme, yükleme-boşaltma ve dorse güvenliği",
        "Araç bakımında kriko, lastik ve yol kenarı riskleri",
        "Trafik kazası, yangın ve acil durum prosedürleri",
    ],
    "turizm_seyahat": [
        "Mutfak, çamaşırhane, teknik servis ve sıcak yüzeyler",
        "Havuz kimyasalları ve biyolojik riskler",
        "Kat hizmetleri, ergonomi ve kayma-düşme",
        "Misafir güvenliği, şiddet ve gece vardiyası",
        "Yangın, kat tahliyesi ve acil durum yönetimi",
    ],
    "universite_yuksekogretim": [
        "Öğrenci, çalışan ve ziyaretçi güvenliği",
        "Laboratuvar, atölye ve spor alanı riskleri",
        "Yangın, deprem, tahliye ve toplanma alanları",
        "Elektrik, merdiven ve kayma-düşme riskleri",
        "Şiddet, psikososyal risk ve acil iletişim",
    ],
    "uretim_imalathane_genel": [
        "Makine ve ekipmanlarla güvenli çalışma",
        "İşyeri içi araç-yaya trafiği ve kör noktalar",
        "Elle taşıma, ergonomi ve güvenli istifleme",
        "Yangın, acil durum ve tahliye uygulamaları",
        "KKD kullanımı, bakım güvenliği ve işyeri düzeni",
    ],
    "yapi_malzemeleri_uretimi": [
        "Çimento ve silika tozu maruziyeti",
        "Konveyör, kırıcı, mikser ve döner ekipmana kapılma",
        "Beton pompası, hortum savrulması ve basınç riskleri",
        "Mobil ekipman, saha trafiği ve kör noktalar",
        "Kimyasal katkı, alkalin yanık ve temizlik işlemleri",
    ],
    "yemek_uretimi_catering": [
        "Kesici, kıyıcı, karıştırıcı ve konveyör makinelerinde güvenlik",
        "Sıcak proses, buhar, kızgın yağ ve yanık riskleri",
        "Soğuk depo, amonyak/CO2 kaçağı ve termal riskler",
        "Temizlik kimyasalları, CIP ve kaygan zemin riskleri",
        "Biyolojik etkenler, hijyen ve ergonomik taşıma riskleri",
    ],
    "yenilenebilir_enerji_gunes_ruzgar": [
        "Yüksek gerilim, ark parlaması ve elektriksel izolasyon",
        "Türbin, jeneratör ve döner ekipman güvenliği",
        "Kazan, buhar, basınçlı sistem ve sıcak yüzeyler",
        "Bakımda kilitleme-etiketleme ve çalışma izinleri",
        "Yangın, kimyasal su şartlandırma ve acil durumlar",
    ],
    "yiyecek_icecek_uretimi": [
        "Kesici, kıyıcı, karıştırıcı ve konveyör makinelerinde güvenlik",
        "Sıcak proses, buhar, kızgın yağ ve yanık riskleri",
        "Soğuk depo, amonyak/CO2 kaçağı ve termal riskler",
        "Temizlik kimyasalları, CIP ve kaygan zemin riskleri",
        "Biyolojik etkenler, hijyen ve ergonomik taşıma riskleri",
    ],
    "yol_altyapi_insaati": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
    "yuksekte_calisma_cephe": [
        "Yüksekte çalışma, düşmeyi önleme ve kurtarma",
        "İskele, merdiven, platform ve kenar koruma güvenliği",
        "Kazı, iksa, göçük ve yeraltı hatları",
        "Vinç, kaldırma ekipmanı ve düşen cisim riskleri",
        "Şantiye içi trafik, iş makineleri ve geçici elektrik",
    ],
}

SEKTOR_ADLARI = {
    code: name
    for _group_name, options in SEKTOR_GRUPLARI
    for code, name in options
}

# Ilk iki konu en kritik, sonraki konu yuksek, son ikisi standart onceliktedir.
SEKTOREL_KONU_AGIRLIKLARI = (1.35, 1.25, 1.15, 1.0, 1.0)

NACE_BOLUM_PROFILLERI = {
    "01": "tarim", "02": "ormancilik", "03": "balikcilik_su_urunleri",
    "05": "madencilik_maden_ocagi", "06": "petrol_dogalgaz",
    "07": "madencilik_maden_ocagi", "08": "madencilik_maden_ocagi",
    "09": "madencilik_maden_ocagi", "10": "gida_uretim", "11": "gida_uretim",
    "12": "tutun_urunleri_uretimi", "13": "tekstil", "14": "tekstil",
    "15": "ayakkabi_deri_uretimi", "16": "ahsap_mobilya",
    "17": "kagit_karton_uretimi", "18": "dijital_baski_matbaa",
    "19": "petrol_rafineri_depolama", "20": "kimya_kimyasal_uretim",
    "21": "ilac_farmasotik_uretim", "22": "plastik_kaucuk",
    "23": "cam_seramik", "24": "demir_celik_hadde",
    "25": "metal_isleme_torna_freze", "26": "elektronik",
    "27": "elektrik_elektronik_uretim", "28": "makine_imalat",
    "29": "otomotiv", "30": "otomotiv", "31": "ahsap_mobilya",
    "32": "genel_uretim", "33": "bakim_onarim_teknik_servis",
    "35": "enerji_uretim", "36": "su_atiksu", "37": "su_atiksu",
    "38": "atik_yonetimi_geri_donusum", "39": "atik_yonetimi_geri_donusum",
    "41": "insaat", "42": "yol_altyapi_insaati", "43": "insaat",
    "46": "depo_lojistik", "47": "perakende", "49": "karayolu_tasimacilik",
    "50": "liman", "51": "havacilik", "52": "depo_lojistik",
    "53": "dagitim_kargo_kurye", "55": "konaklama_otel_pansiyon",
    "56": "restoran", "58": "basin_yayin_medya", "59": "basin_yayin_medya",
    "60": "basin_yayin_medya", "61": "telekom", "62": "bilisim_yazilim_it",
    "63": "bilisim_yazilim_it", "64": "banka_finans", "65": "sigorta_broker",
    "66": "banka_finans", "68": "ofis", "69": "ofis", "70": "ofis",
    "71": "muhendislik_proje_ofisi", "72": "laboratuvar",
    "73": "reklam_tabela_baski", "74": "ofis", "75": "veterinerlik",
    "77": "ofis", "78": "ofis", "79": "turizm_seyahat",
    "80": "guvenlik_hizmetleri", "81": "temizlik_facility_management",
    "82": "ofis", "84": "belediye_kamu_hizmetleri",
    "85": "egitim_kurumu", "86": "saglik_hastane_klinik",
    "87": "saglik_hastane_klinik", "88": "saglik_hastane_klinik",
    "90": "organizasyon_etkinlik", "91": "ofis", "92": "ofis",
    "93": "spor_tesisi_fitness", "94": "ofis",
    "95": "bakim_onarim_teknik_servis", "96": "ofis",
    "97": "temizlik", "98": "temizlik", "99": "ofis",
}

NACE_ON_EK_PROFILLERI = {
    "01.48.01": "aricilik", "01.48": "hayvancilik", "01.4": "hayvancilik",
    "01.62": "hayvancilik",
    "10.51": "sut_sut_urunleri", "10.71": "firin_unlu_mamuller",
    "10.72": "firin_unlu_mamuller", "13.30": "boyahaneler_boya_uretimi",
    "15.11": "ayakkabi_deri_uretimi", "18.": "dijital_baski_matbaa",
    "20.30": "boyahaneler_boya_uretimi", "20.41": "kozmetik_temizlik_urunleri",
    "20.42": "kozmetik_temizlik_urunleri", "20.51": "petrol_rafineri_depolama",
    "20.59.17": "patlayici", "23.1": "cam_seramik",
    "23.2": "seramik_fayans", "23.3": "seramik_fayans",
    "23.5": "beton_cimento_hazir_beton", "23.6": "beton_cimento_hazir_beton",
    "25.30": "patlayici", "25.53": "metal_isleme_torna_freze",
    "27.20": "aku_uretimi", "27.3": "kablo_tel_uretimi",
    "28.22": "is_makinesi_agir_ekipman",
    "28.24": "makine_imalat", "28.92": "is_makinesi_agir_ekipman",
    "30.11": "gemi_insa_tersane", "30.12": "gemi_insa_tersane",
    "30.13": "gemi_insa_tersane", "30.20": "demiryolu",
    "30.31": "havacilik", "30.32": "havacilik",
    "32.11": "metal_isleme_torna_freze", "32.12": "kuyumculuk_mucevher",
    "32.13": "kuyumculuk_mucevher", "35.15": "ofis", "35.23": "ofis",
    "35.40": "ofis", "38.3": "atik_geri_donusum",
    "42.1": "yol_altyapi_insaati", "42.2": "yol_altyapi_insaati",
    "43.21": "elektrik_tesisat_pano_montaj",
    "43.22": "bakim_onarim_teknik_servis", "43.60": "ofis",
    "43.99": "insaat_santiye",
    "46.11": "ticaret_aracilik_ofis", "46.12": "ticaret_aracilik_ofis",
    "46.13": "ticaret_aracilik_ofis", "46.14": "ticaret_aracilik_ofis",
    "46.15": "ticaret_aracilik_ofis", "46.16": "ticaret_aracilik_ofis",
    "46.17": "ticaret_aracilik_ofis", "46.18": "ticaret_aracilik_ofis",
    "46.19": "ticaret_aracilik_ofis", "46.21": "tarimsal_urun_toptan",
    "46.22": "tarimsal_urun_toptan", "46.23": "canli_hayvan_toptan",
    "46.24": "tekstil_deri_toptan", "46.31": "gida_toptan_depo",
    "46.32": "gida_toptan_depo", "46.33": "gida_toptan_depo",
    "46.34": "gida_toptan_depo", "46.35": "gida_toptan_depo",
    "46.36": "gida_toptan_depo", "46.37": "gida_toptan_depo",
    "46.38": "gida_toptan_depo", "46.39": "gida_toptan_depo",
    "46.41": "tekstil_deri_toptan", "46.42": "tekstil_deri_toptan",
    "46.43": "elektrik_elektronik_toptan",
    "46.44.02": "kimyasal_toptan_depo", "46.44.04": "kimyasal_toptan_depo",
    "46.44": "mobilya_ev_esyasi_toptan", "46.45": "kimyasal_toptan_depo",
    "46.46": "ecza_medikal_toptan", "46.47": "mobilya_ev_esyasi_toptan",
    "46.48": "kuyumculuk_mucevher", "46.49": "mobilya_ev_esyasi_toptan",
    "46.50": "elektrik_elektronik_toptan", "46.61": "makine_ekipman_toptan",
    "46.62": "makine_ekipman_toptan", "46.63": "makine_ekipman_toptan",
    "46.64.09": "elektrik_elektronik_toptan", "46.64.10": "patlayici",
    "46.64.15": "elektrik_elektronik_toptan", "46.64": "makine_ekipman_toptan",
    "46.71": "otomotiv_toptan", "46.72": "otomotiv_toptan",
    "46.73": "otomotiv_toptan", "46.81": "yakit_toptan_depo",
    "46.82": "metal_yapi_elemanlari_toptan",
    "46.83.06": "metal_yapi_elemanlari_toptan", "46.83": "yapi_malzemeleri_toptan",
    "46.84": "yapi_malzemeleri_toptan", "46.85": "kimyasal_toptan_depo",
    "46.86.03": "kagit_karton_uretimi", "46.86.04": "tekstil_deri_toptan",
    "46.86.05": "kuyumculuk_mucevher", "46.86": "genel_toptan_depo",
    "46.87": "atik_hurda_toptan", "46.89": "genel_toptan_depo",
    "46.90": "genel_toptan_depo",
    "47.30": "akaryakit_lpg_dolum_istasyonu",
    "47.52": "hirdavat_yapi_market", "47.73": "eczane_medikal_satis",
    "47.74": "eczane_medikal_satis", "47.75": "kimyasal_perakende",
    "47.76.01": "canli_hayvan_toptan", "47.76.02": "tarimsal_urun_toptan",
    "47.76.03": "kimyasal_perakende", "47.76.04": "canli_hayvan_toptan",
    "47.76.05": "canli_hayvan_toptan", "47.76.06": "tarimsal_urun_toptan",
    "47.76.07": "canli_hayvan_toptan", "47.77": "kuyumculuk_mucevher",
    "47.78.02": "yakit_toptan_depo", "47.78.09": "yakit_toptan_depo",
    "47.78.10": "yakit_toptan_depo", "47.78.15": "kimyasal_perakende",
    "47.78.31": "yakit_toptan_depo", "47.81": "otomotiv_toptan",
    "47.82": "otomotiv_toptan", "47.83": "otomotiv_toptan",
    "47.91": "ticaret_aracilik_ofis", "47.92": "ticaret_aracilik_ofis",
    "49.1": "demiryolu", "49.2": "demiryolu", "49.5": "petrol_dogalgaz",
    "52.10": "depo_lojistik", "52.21": "karayolu_tasimacilik",
    "52.22": "liman", "52.23": "havalimani_yer_hizmetleri",
    "52.31": "ofis", "52.32": "ofis",
    "53.1": "dagitim_kargo_kurye", "53.2": "kurye", "53.30": "ofis",
    "58.29": "bilisim_yazilim_it", "61.20": "ofis", "66.22": "sigorta_broker",
    "56.": "restoran_cafe_mutfak", "69.1": "avukatlik_hukuk_burosu",
    "68.12": "muhendislik_proje_ofisi", "71.2": "laboratuvar_analiz",
    "72.20": "ofis", "73.20": "ofis", "73.30": "ofis",
    "74.20": "basin_yayin_medya", "75.": "veterinerlik",
    "77.11": "otomotiv_toptan", "77.12": "otomotiv_toptan",
    "77.21": "perakende", "77.22": "perakende",
    "77.31": "ekipman_kiralama", "77.32": "ekipman_kiralama",
    "77.33": "ekipman_kiralama", "77.34": "ekipman_kiralama",
    "77.35": "ekipman_kiralama", "77.39": "ekipman_kiralama",
    "81.22.04": "yuksekte_calisma_cephe", "81.30": "tarim",
    "82.30": "organizasyon_etkinlik", "82.92": "depo_lojistik",
    "85.40": "universite_yuksekogretim", "85.51": "spor_tesisi_fitness",
    "85.53": "karayolu_tasimacilik",
    "86.23": "tip_dis_klinigi", "86.91": "laboratuvar_analiz",
    "88.91": "egitim_kurumu", "90.11": "ofis", "90.12": "genel_uretim",
    "90.13": "ofis", "91.30": "insaat",
    "91.41": "hayvanat_bahcesi", "91.42": "ormancilik",
    "92.00": "guvenlik_hizmetleri", "93.21": "organizasyon_etkinlik",
    "94.91": "organizasyon_etkinlik", "95.31": "otomotiv_servis_bakim",
    "95.32": "otomotiv_servis_bakim", "96.10": "camasirhane_kuru_temizleme",
    "96.21": "guzellik_kuafor_spa", "96.22": "guzellik_kuafor_spa",
    "96.23": "guzellik_kuafor_spa", "96.30": "cenaze_hizmetleri",
    "96.91": "temizlik", "96.99.02": "depo_lojistik",
    "96.99.04": "veterinerlik", "96.99.05": "karayolu_tasimacilik",
    "96.99.07": "temizlik", "96.99.14": "organizasyon_etkinlik",
    "96.99.15": "organizasyon_etkinlik", "96.99.99": "guzellik_kuafor_spa",
}


def nace_profil_kodu_getir(nace_kodu):
    nace_kodu = str(nace_kodu or "").strip()
    for on_ek in sorted(NACE_ON_EK_PROFILLERI, key=len, reverse=True):
        if nace_kodu.startswith(on_ek):
            return NACE_ON_EK_PROFILLERI[on_ek]
    return NACE_BOLUM_PROFILLERI.get(nace_kodu[:2], "")


def sektor_secenkleri():
    return [(code, name) for _group, options in SEKTOR_GRUPLARI for code, name in options]


def sektor_adi_getir(code):
    return SEKTOR_ADLARI.get(str(code or "").strip(), "")


def sektorel_konulari_getir(code):
    return list(SEKTOREL_EGITIM_KONULARI.get(str(code or "").strip(), []))


def sektor_gecerli_mi(code):
    code = str(code or "").strip()
    return bool(code and code in SEKTOR_ADLARI and code in SEKTOREL_EGITIM_KONULARI)
