"""Faz 3A: uygunsuzluk, DÃ–F ve kanÄ±t zinciri

Revision ID: 0072_ibys_nonconformity_dof
Revises: 0071
"""
from alembic import op
import sqlalchemy as sa
revision="0072_ibys_nonconformity_dof"
down_revision="0071"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("ibys_nonconformities",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("osgb_id",sa.Integer(),sa.ForeignKey("osgb_organizations.id"),nullable=False),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id"),nullable=False),sa.Column("source_module",sa.String(60),nullable=False),sa.Column("source_record_id",sa.String(100)),sa.Column("title",sa.String(240),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("category",sa.String(80),nullable=False,server_default="general"),sa.Column("priority",sa.String(20),nullable=False,server_default="medium"),sa.Column("risk_level",sa.String(30)),sa.Column("status",sa.String(30),nullable=False,server_default="open"),sa.Column("due_date",sa.Date()),sa.Column("assigned_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("reviewer_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("closed_at",sa.DateTime()),sa.Column("closed_by_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("closure_note",sa.String(2000)),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("osgb_id","uuid",name="uq_ibys_nc_osgb_uuid"))
    op.create_index("ix_ibys_nc_company_status","ibys_nonconformities",["company_id","status"]); op.create_index("ix_ibys_nc_due","ibys_nonconformities",["due_date"]); op.create_index("ix_ibys_nc_source","ibys_nonconformities",["source_module","source_record_id"])
    op.create_table("ibys_corrective_actions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False,unique=True),sa.Column("nonconformity_id",sa.Integer(),sa.ForeignKey("ibys_nonconformities.id"),nullable=False),sa.Column("osgb_id",sa.Integer(),sa.ForeignKey("osgb_organizations.id"),nullable=False),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id"),nullable=False),sa.Column("sequence_no",sa.Integer(),nullable=False),sa.Column("action_type",sa.String(30),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("assignee_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("due_date",sa.Date(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("completion_note",sa.String(2000)),sa.Column("completed_at",sa.DateTime()),sa.Column("reviewed_by_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("reviewed_at",sa.DateTime()),sa.Column("review_note",sa.String(2000)),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("nonconformity_id","sequence_no",name="uq_ibys_action_nc_seq"))
    op.create_index("ix_ibys_action_company_status","ibys_corrective_actions",["company_id","status"]); op.create_index("ix_ibys_action_assignee_due","ibys_corrective_actions",["assignee_user_id","due_date"]); op.create_index("ix_ibys_action_nc","ibys_corrective_actions",["nonconformity_id"])
    op.create_table("ibys_action_evidence",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("action_id",sa.Integer(),sa.ForeignKey("ibys_corrective_actions.id"),nullable=False),sa.Column("osgb_id",sa.Integer(),sa.ForeignKey("osgb_organizations.id"),nullable=False),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id"),nullable=False),sa.Column("evidence_type",sa.String(30),nullable=False),sa.Column("description",sa.String(2000),nullable=False),sa.Column("storage_path",sa.String(500)),sa.Column("sha256",sa.String(64)),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_index("ix_ibys_evidence_action","ibys_action_evidence",["action_id"])
    op.create_table("ibys_action_status_history",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("action_id",sa.Integer(),sa.ForeignKey("ibys_corrective_actions.id"),nullable=False),sa.Column("osgb_id",sa.Integer(),sa.ForeignKey("osgb_organizations.id"),nullable=False),sa.Column("from_status",sa.String(30)),sa.Column("to_status",sa.String(30),nullable=False),sa.Column("note",sa.String(1000)),sa.Column("actor_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_index("ix_ibys_history_action_created","ibys_action_status_history",["action_id","created_at"])

def downgrade():
    op.drop_table("ibys_action_status_history"); op.drop_table("ibys_action_evidence"); op.drop_table("ibys_corrective_actions"); op.drop_table("ibys_nonconformities")
