import React,{useEffect,useState} from 'react';
import {Camera,CheckCircle2,ClipboardCheck,ShieldAlert} from 'lucide-react';
import {api,uploadFile} from './api';
import {FieldInspectionPremiumPage} from './field_inspection_phase_d';

const touch={minHeight:52,fontSize:16,borderRadius:14};

export function FieldPwaHub({user}){
  const[tab,setTab]=useState('ptw'); const[companies,setCompanies]=useState([]); const[companyId,setCompanyId]=useState(user.company_id||'');
  const[permits,setPermits]=useState([]); const[meta,setMeta]=useState(null); const[busy,setBusy]=useState(false); const[err,setErr]=useState(''); const[msg,setMsg]=useState('');
  const[close,setClose]=useState({permit_id:'',note:'',photo:null});
  const[incident,setIncident]=useState({event_date:new Date().toISOString().slice(0,10),location:'',short_summary:'',detail:'',classification:'',photo:null});
  const canIncident=['global_admin','safety_specialist'].includes(user.role);
  const canInspect=user.role==='safety_specialist';
  async function load(cid=companyId){if(!cid)return;try{const [p,m]=await Promise.all([api(`/field-mobile/ptw?company_id=${cid}`),api('/incidents/meta').catch(()=>null)]);setPermits(p.items||[]);setMeta(m);if(m?.classifications?.length&&!incident.classification)setIncident(v=>({...v,classification:m.classifications[0]}))}catch(e){setErr(e.message)}}
  useEffect(()=>{api('/companies').then(rows=>{setCompanies(rows||[]);const id=companyId||rows?.[0]?.id||'';setCompanyId(String(id));if(id)void load(id)}).catch(e=>setErr(e.message))},[]);
  async function closePermit(e){e.preventDefault();if(!close.permit_id)return;setBusy(true);setErr('');setMsg('');try{const row=await api(`/field-mobile/ptw/${close.permit_id}/close`,{method:'POST',body:JSON.stringify({note:close.note||null})});if(close.photo)await uploadFile(`/field-mobile/evidence/work_permit/${row.id}`,close.photo);setMsg(`${row.permit_no||'Çalışma izni'} saha kapanışı tamamlandı.`);setClose({permit_id:'',note:'',photo:null});await load()}catch(x){setErr(x.message)}finally{setBusy(false)}}
  async function saveIncident(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const payload={company_id:Number(companyId),event_type:'ramak_kala',event_date:incident.event_date,location:incident.location,short_summary:incident.short_summary,detail:incident.detail,classification:incident.classification||meta?.classifications?.[0]||'Ramak Kala',would_have_injured:true,probability:3,severity:3};const row=await api('/incidents',{method:'POST',body:JSON.stringify(payload)});if(incident.photo)await uploadFile(`/field-mobile/evidence/incident/${row.id}`,incident.photo);setMsg(`${row.form_no||'Ramak kala'} kaydı ve fotoğraf kanıtı kaydedildi.`);setIncident(v=>({...v,location:'',short_summary:'',detail:'',photo:null}))}catch(x){setErr(x.message)}finally{setBusy(false)}}
  if(tab==='inspection'&&canInspect)return <><button className="secondary" onClick={()=>setTab('ptw')} style={{...touch,marginBottom:12}}>← Saha Hızlı İşlem</button><FieldInspectionPremiumPage user={user}/></>;
  return <>
    <div className="page-title"><h3><Camera size={20}/> Saha Hızlı İşlem</h3></div>
    <section className="panel">
      <div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:16}}><button style={touch} onClick={()=>setTab('ptw')}><CheckCircle2 size={18}/> PTW Kapat</button>{canIncident&&<button className="secondary" style={touch} onClick={()=>setTab('incident')}><ShieldAlert size={18}/> Ramak Kala + Foto</button>}{canInspect&&<button className="secondary" style={touch} onClick={()=>setTab('inspection')}><ClipboardCheck size={18}/> Saha Denetimi</button>}</div>
      {!user.company_id&&<label className="field" style={{maxWidth:480}}><span>İşyeri</span><select style={touch} value={companyId} onChange={e=>{setCompanyId(e.target.value);void load(e.target.value)}}><option value="">Seçiniz</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
      {err&&<div className="error">{err}</div>}{msg&&<div className="success">{msg}</div>}
      {tab==='ptw'&&<form onSubmit={closePermit} style={{display:'grid',gap:14,maxWidth:720}}><h3>Aktif çalışma iznini sahada kapat</h3><label className="field"><span>Aktif izin</span><select required style={touch} value={close.permit_id} onChange={e=>setClose({...close,permit_id:e.target.value})}><option value="">Seçiniz</option>{permits.map(p=><option key={p.id} value={p.id}>{p.permit_no} · {p.location}</option>)}</select></label><label className="field"><span>Kapanış notu</span><textarea rows={3} value={close.note} onChange={e=>setClose({...close,note:e.target.value})}/></label><label className="field"><span>Kamera kanıtı (isteğe bağlı)</span><input style={touch} type="file" accept="image/*" capture="environment" onChange={e=>setClose({...close,photo:e.target.files?.[0]||null})}/></label><button disabled={busy} style={touch}>Saha kapanışını onayla</button></form>}
      {tab==='incident'&&canIncident&&<form onSubmit={saveIncident} style={{display:'grid',gap:14,maxWidth:720}}><h3>Ramak kala olayını fotoğrafla kaydet</h3><label className="field"><span>Tarih</span><input style={touch} type="date" required max={new Date().toISOString().slice(0,10)} value={incident.event_date} onChange={e=>setIncident({...incident,event_date:e.target.value})}/></label><label className="field"><span>Yer</span><input style={touch} required value={incident.location} onChange={e=>setIncident({...incident,location:e.target.value})}/></label><label className="field"><span>Sınıflandırma</span><select style={touch} value={incident.classification} onChange={e=>setIncident({...incident,classification:e.target.value})}>{(meta?.classifications||[]).map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="field"><span>Kısa özet (en az 20 karakter)</span><textarea rows={2} required minLength={20} value={incident.short_summary} onChange={e=>setIncident({...incident,short_summary:e.target.value})}/></label><label className="field"><span>Detay (en az 30 karakter)</span><textarea rows={4} required minLength={30} value={incident.detail} onChange={e=>setIncident({...incident,detail:e.target.value})}/></label><label className="field"><span>Kamera fotoğrafı</span><input style={touch} type="file" accept="image/*" capture="environment" onChange={e=>setIncident({...incident,photo:e.target.files?.[0]||null})}/></label><button disabled={busy} style={touch}>Ramak kala kaydını oluştur</button></form>}
    </section>
  </>;
}
