import {useEffect, useState} from "react";
import {api} from "./api";

export function VisitorsPage() {
  const [companies, setCompanies] = useState([]), [rows, setRows] = useState([]), [companyId, setCompanyId] = useState(""), [qr, setQr] = useState(""), [error, setError] = useState("");
  const [form, setForm] = useState({full_name: "", organization: "", phone: "", purpose: "", valid_from: "", valid_until: ""});
  async function load() { const data = await api(companyId ? `/visitors?company_id=${companyId}` : "/visitors"); setRows(data.items || []); }
  useEffect(() => { Promise.all([api("/companies"), api("/visitors")]).then(([c, v]) => {setCompanies(Array.isArray(c) ? c : c.items || []); setRows(v.items || []);}).catch((ex) => setError(ex.message)); }, []);
  useEffect(() => { if (companyId) load().catch((ex) => setError(ex.message)); }, [companyId]);
  function update(name, value) { setForm((current) => ({...current, [name]: value})); }
  async function create(event) { event.preventDefault(); try { const result = await api("/visitors", {method: "POST", body: JSON.stringify({...form, company_id: Number(companyId), valid_from: new Date(form.valid_from).toISOString(), valid_until: new Date(form.valid_until).toISOString()})}); setQr(result.qr_token || ""); setForm({full_name: "", organization: "", phone: "", purpose: "", valid_from: "", valid_until: ""}); await load(); } catch (ex) { setError(ex.message); } }
  async function transition(id, action) { try { await api(`/visitors/${id}/${action}`, {method: "POST"}); await load(); } catch (ex) { setError(ex.message); } }
  return <section className="page-shell"><div className="page-title"><h3>Ziyaretçi Yönetimi</h3><span className="badge ok">QR</span></div><section className="panel">{error && <p className="error">{error}</p>}{qr && <div className="field-ok-msg">Geçici QR token oluşturuldu: <code>{qr}</code></div>}<form className="form-grid" onSubmit={create}><label className="field"><span>İşyeri</span><select required value={companyId} onChange={(event) => setCompanyId(event.target.value)}><option value="">İşyeri seçin</option>{companies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Ad soyad</span><input required value={form.full_name} onChange={(event) => update("full_name", event.target.value)} /></label><label className="field"><span>Kurum</span><input value={form.organization} onChange={(event) => update("organization", event.target.value)} /></label><label className="field"><span>Telefon</span><input value={form.phone} onChange={(event) => update("phone", event.target.value)} /></label><label className="field"><span>Ziyaret amacı</span><input required value={form.purpose} onChange={(event) => update("purpose", event.target.value)} /></label><label className="field"><span>Geçerlilik başlangıcı</span><input required type="datetime-local" value={form.valid_from} onChange={(event) => update("valid_from", event.target.value)} /></label><label className="field"><span>Geçerlilik bitişi</span><input required type="datetime-local" value={form.valid_until} onChange={(event) => update("valid_until", event.target.value)} /></label><div className="form-actions"><button type="submit">Geçiş oluştur</button></div></form><div className="table-wrap"><table><thead><tr><th>Ziyaretçi</th><th>İşyeri</th><th>Amaç</th><th>Geçerlilik</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.full_name}</td><td>{companies.find((item) => item.id === row.company_id)?.name || row.company_id}</td><td>{row.purpose}</td><td>{row.valid_until}</td><td>{row.status}</td><td>{row.status === "issued" && <button type="button" onClick={() => transition(row.id, "check-in")}>Giriş</button>}{row.status === "inside" && <button type="button" onClick={() => transition(row.id, "check-out")}>Çıkış</button>}</td></tr>)}</tbody></table></div></section></section>;
}
