import {useEffect, useState} from "react";
import {api} from "./api";

const types = {hot_work: "Sıcak iş", work_at_height: "Yüksekte çalışma", confined_space: "Kapalı alan", electrical: "Elektrik", general: "Genel"};
const statuses = {draft: "Taslak", pending_approval: "Onay bekliyor", active: "Aktif", suspended: "Askıda", expired: "Süresi doldu", closed: "Kapatıldı", rejected: "Reddedildi", cancelled: "İptal edildi"};

export function WorkPermitsPage({user}) {
  const [companies, setCompanies] = useState([]), [employees, setEmployees] = useState([]), [contractors, setContractors] = useState([]), [approvers, setApprovers] = useState([]), [inspections, setInspections] = useState([]), [rows, setRows] = useState([]), [selected, setSelected] = useState(null);
  const [companyId, setCompanyId] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [form, setForm] = useState({permit_type: "general", description: "", location: "", valid_from: "", valid_until: "", employee_ids: [], approver_user_ids: [], field_inspection_id: null, notes: ""});
  async function load() { const data = await api(companyId ? `/work-permits?company_id=${companyId}` : "/work-permits"); setRows(data.items || []); }
  useEffect(() => { Promise.all([api("/companies"), api("/work-permits")]).then(([c, p]) => {setCompanies(Array.isArray(c) ? c : c.items || []); setRows(p.items || []);}).catch((ex) => setError(ex.message)); }, []);
  useEffect(() => { if (!companyId) {setEmployees([]); setContractors([]); setApprovers([]); setInspections([]); return;} Promise.all([api(`/work-permits/employees?company_id=${companyId}`), api(`/contractors?company_id=${companyId}`), api(`/work-permits/approvers?company_id=${companyId}`), api(`/work-permits/field-inspections?company_id=${companyId}`)]).then(([employeeData, contractorData, approverData, inspectionData]) => {setEmployees(employeeData.items || []); setContractors(contractorData.items || []); setApprovers(approverData.items || []); setInspections(inspectionData.items || []);}).catch(() => {setEmployees([]); setContractors([]); setApprovers([]); setInspections([]);}); load().catch(() => {}); }, [companyId]);
  function update(name, value) { setForm((current) => ({...current, [name]: value})); }
  async function create(event) { event.preventDefault(); setBusy(true); setError(""); try { await api("/work-permits", {method: "POST", body: JSON.stringify({...form, company_id: Number(companyId), employee_ids: form.employee_ids.map(Number), approver_user_ids: form.approver_user_ids.map(Number), contractor_id: form.contractor_id ? Number(form.contractor_id) : null, field_inspection_id: form.field_inspection_id ? Number(form.field_inspection_id) : null, valid_from: new Date(form.valid_from).toISOString(), valid_until: new Date(form.valid_until).toISOString()})}); update("description", ""); update("location", ""); await load(); } catch (ex) { setError(ex.message); } finally { setBusy(false); } }
  async function transition(id, action) { setBusy(true); try { await api(`/work-permits/${id}/${action}`, {method: "POST", body: JSON.stringify({})}); await load(); } catch (ex) { setError(ex.message); } finally { setBusy(false); } }
  async function saveControls(event) { event.preventDefault(); if (!selected) return; setBusy(true); try { const data = Array.from(event.currentTarget.elements).filter((element) => element.dataset.control).map((element) => ({control_type: element.dataset.control, status: element.value})); await api(`/work-permits/${selected.id}/controls`, {method: "PUT", body: JSON.stringify(data)}); setSelected(null); await load(); } catch (ex) { setError(ex.message); } finally { setBusy(false); } }
  return <section className="page-shell"><div className="page-title"><h3>Çalışma İzinleri</h3><span className="badge ok">PTW</span></div><section className="panel">
    {error && <p className="error">{error}</p>}
    <div className="report-grid"><article className="metric"><span>Toplam izin</span><strong>{rows.length}</strong></article><article className="metric"><span>Aktif izin</span><strong>{rows.filter((row) => row.status === "active").length}</strong></article><article className="metric"><span>Onay bekleyen</span><strong>{rows.filter((row) => row.status === "pending_approval").length}</strong></article></div>
    <form className="form-grid" onSubmit={create}>
      <label className="field"><span>İşyeri</span><select required value={companyId} onChange={(event) => setCompanyId(event.target.value)}><option value="">İşyeri seçin</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label>
      <label className="field"><span>İzin türü</span><select value={form.permit_type} onChange={(event) => update("permit_type", event.target.value)}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="field"><span>İş tanımı</span><input required value={form.description} onChange={(event) => update("description", event.target.value)} /></label>
      <label className="field"><span>Lokasyon</span><input required value={form.location} onChange={(event) => update("location", event.target.value)} /></label>
      <label className="field"><span>Başlangıç</span><input required type="datetime-local" value={form.valid_from} onChange={(event) => update("valid_from", event.target.value)} /></label>
      <label className="field"><span>Bitiş</span><input required type="datetime-local" value={form.valid_until} onChange={(event) => update("valid_until", event.target.value)} /></label>
      <label className="field"><span>Çalışanlar</span><select multiple value={form.employee_ids} onChange={(event) => update("employee_ids", Array.from(event.target.selectedOptions, (option) => option.value))}>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}{employee.job_title ? ` · ${employee.job_title}` : ""}</option>)}</select></label>
      <label className="field"><span>Onaylayan(lar)</span><select multiple value={form.approver_user_ids} onChange={(event) => update("approver_user_ids", Array.from(event.target.selectedOptions, (option) => option.value))}>{approvers.map((approver) => <option key={approver.id} value={approver.id}>{approver.full_name}</option>)}</select></label>
      <label className="field"><span>Saha denetimi</span><select value={form.field_inspection_id || ""} onChange={(event) => update("field_inspection_id", event.target.value || null)}><option value="">Bağlantı yok</option>{inspections.map((inspection) => <option key={inspection.id} value={inspection.id}>{inspection.inspection_no} · {inspection.inspection_date}</option>)}</select></label>
      <label className="field"><span>Taşeron</span><select value={form.contractor_id || ""} onChange={(event) => update("contractor_id", event.target.value || null)}><option value="">Taşeron yok</option>{contractors.map((contractor) => <option key={contractor.id} value={contractor.id}>{contractor.name}</option>)}</select></label>
      <label className="field"><span>Notlar</span><input value={form.notes} onChange={(event) => update("notes", event.target.value)} /></label>
      <div className="form-actions"><button type="submit" disabled={busy}>Kaydet</button></div>
    </form>
    <div className="table-wrap"><table><thead><tr><th>İzin No</th><th>Tür</th><th>Lokasyon</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.permit_no}</td><td>{types[row.permit_type] || row.permit_type}</td><td>{row.location}</td><td>{statuses[row.status] || row.status}</td><td className="actions"><button type="button" onClick={() => setSelected(row)}>Kontroller</button>{row.status === "draft" && <button type="button" onClick={() => transition(row.id, "submit")} disabled={busy}>Onaya gönder</button>}{row.status === "pending_approval" && <button type="button" onClick={() => transition(row.id, "approve")} disabled={busy}>Onayla</button>}{row.status === "active" && !row.opening_checked_at && <button type="button" onClick={() => transition(row.id, "open")} disabled={busy}>Sahayı aç</button>}{row.status === "active" && row.opening_checked_at && <button type="button" onClick={() => transition(row.id, "close")} disabled={busy}>Kapat</button>}{!["closed", "rejected", "cancelled"].includes(row.status) && <button type="button" onClick={() => transition(row.id, "cancel")} disabled={busy}>İzni iptal et</button>}</td></tr>)}</tbody></table></div>
    {selected && <form className="form-grid" onSubmit={saveControls}><h4>PTW operasyon kontrolleri: {selected.permit_no}</h4>{[["loto", "LOTO / enerji izolasyonu"], ["gas_measurement", "Gaz ölçümü"], ["ppe", "KKD kontrolü"], ["equipment", "Ekipman kontrolü"], ["emergency_preparedness", "Acil durum hazırlığı"], ["competency", "Yetkinlik belgesi"]].map(([value, label]) => <label className="field" key={value}><span>{label}</span><select data-control={value} defaultValue={selected.controls?.find((control) => control.control_type === value)?.status || "pending"}><option value="pending">Kontrol bekliyor</option><option value="passed">Uygun</option><option value="failed">Uygunsuz</option><option value="not_applicable">Uygulanamaz</option></select></label>)}<div className="form-actions"><button type="submit" disabled={busy}>Kontrolleri kaydet</button><button type="button" onClick={() => setSelected(null)}>Vazgeç</button></div></form>}
  </section></section>;
}